/* Generated by Yosys 0.61 (git sha1 5ae48ee25f298f7b3c8c0de30bd2f85a94133031, clang++ 17.0.0 -fPIC -O3) */

(* dynports =  1  *)
(* hdlname = "std_const" *)
(* src = "/tmp/domain_clean_chirho.v:1233.1-1240.10" *)
module \$paramod$25c94d4f8057fb6df438ef354e0c89df8651fe3a\std_const (out);
  (* src = "/tmp/domain_clean_chirho.v:1237.29-1237.32" *)
  output [63:0] out;
  wire [63:0] out;
  assign out = 64'h00000000000000ff;
endmodule

(* dynports =  1  *)
(* hdlname = "std_const" *)
(* src = "/tmp/domain_clean_chirho.v:1233.1-1240.10" *)
module \$paramod$48af5e9059f5cb939f41deb7ac38ebaea4b9f561\std_const (out);
  (* src = "/tmp/domain_clean_chirho.v:1237.29-1237.32" *)
  output [63:0] out;
  wire [63:0] out;
  assign out = 64'h00000000000000f0;
endmodule

(* dynports =  1  *)
(* hdlname = "std_const" *)
(* src = "/tmp/domain_clean_chirho.v:1233.1-1240.10" *)
module \$paramod$671ddf9215aeccc75d9ce31d476d82165dd4dc10\std_const (out);
  (* src = "/tmp/domain_clean_chirho.v:1237.29-1237.32" *)
  output [63:0] out;
  wire [63:0] out;
  assign out = 64'hffffffffffffffff;
endmodule

(* dynports =  1  *)
(* hdlname = "std_const" *)
(* src = "/tmp/domain_clean_chirho.v:1233.1-1240.10" *)
module \$paramod$b7c52f579af5ece61583054911856cac9593fccf\std_const (out);
  (* src = "/tmp/domain_clean_chirho.v:1237.29-1237.32" *)
  output [63:0] out;
  wire [63:0] out;
  assign out = 64'h0000000000000000;
endmodule

(* dynports =  1  *)
(* hdlname = "std_and" *)
(* src = "/tmp/domain_clean_chirho.v:852.1-860.10" *)
module \$paramod\std_and\WIDTH=s32'00000000000000000000000001000000 (left, right, out);
  (* src = "/tmp/domain_clean_chirho.v:855.47-855.51" *)
  input [63:0] left;
  wire [63:0] left;
  (* src = "/tmp/domain_clean_chirho.v:856.47-856.52" *)
  input [63:0] right;
  wire [63:0] right;
  (* src = "/tmp/domain_clean_chirho.v:857.29-857.32" *)
  output [63:0] out;
  wire [63:0] out;
  assign out[0] = right[0] & left[0];
  assign out[1] = right[1] & left[1];
  assign out[2] = right[2] & left[2];
  assign out[3] = right[3] & left[3];
  assign out[4] = right[4] & left[4];
  assign out[5] = right[5] & left[5];
  assign out[6] = right[6] & left[6];
  assign out[7] = right[7] & left[7];
  assign out[8] = right[8] & left[8];
  assign out[9] = right[9] & left[9];
  assign out[10] = right[10] & left[10];
  assign out[11] = right[11] & left[11];
  assign out[12] = right[12] & left[12];
  assign out[13] = right[13] & left[13];
  assign out[14] = right[14] & left[14];
  assign out[15] = right[15] & left[15];
  assign out[16] = right[16] & left[16];
  assign out[17] = right[17] & left[17];
  assign out[18] = right[18] & left[18];
  assign out[19] = right[19] & left[19];
  assign out[20] = right[20] & left[20];
  assign out[21] = right[21] & left[21];
  assign out[22] = right[22] & left[22];
  assign out[23] = right[23] & left[23];
  assign out[24] = right[24] & left[24];
  assign out[25] = right[25] & left[25];
  assign out[26] = right[26] & left[26];
  assign out[27] = right[27] & left[27];
  assign out[28] = right[28] & left[28];
  assign out[29] = right[29] & left[29];
  assign out[30] = right[30] & left[30];
  assign out[31] = right[31] & left[31];
  assign out[32] = right[32] & left[32];
  assign out[33] = right[33] & left[33];
  assign out[34] = right[34] & left[34];
  assign out[35] = right[35] & left[35];
  assign out[36] = right[36] & left[36];
  assign out[37] = right[37] & left[37];
  assign out[38] = right[38] & left[38];
  assign out[39] = right[39] & left[39];
  assign out[40] = right[40] & left[40];
  assign out[41] = right[41] & left[41];
  assign out[42] = right[42] & left[42];
  assign out[43] = right[43] & left[43];
  assign out[44] = right[44] & left[44];
  assign out[45] = right[45] & left[45];
  assign out[46] = right[46] & left[46];
  assign out[47] = right[47] & left[47];
  assign out[48] = right[48] & left[48];
  assign out[49] = right[49] & left[49];
  assign out[50] = right[50] & left[50];
  assign out[51] = right[51] & left[51];
  assign out[52] = right[52] & left[52];
  assign out[53] = right[53] & left[53];
  assign out[54] = right[54] & left[54];
  assign out[55] = right[55] & left[55];
  assign out[56] = right[56] & left[56];
  assign out[57] = right[57] & left[57];
  assign out[58] = right[58] & left[58];
  assign out[59] = right[59] & left[59];
  assign out[60] = right[60] & left[60];
  assign out[61] = right[61] & left[61];
  assign out[62] = right[62] & left[62];
  assign out[63] = right[63] & left[63];
endmodule

(* dynports =  1  *)
(* hdlname = "std_eq" *)
(* src = "/tmp/domain_clean_chirho.v:912.1-920.10" *)
module \$paramod\std_eq\WIDTH=s32'00000000000000000000000001000000 (left, right, out);
  (* src = "/tmp/domain_clean_chirho.v:915.35-915.39" *)
  input [63:0] left;
  wire [63:0] left;
  (* src = "/tmp/domain_clean_chirho.v:916.35-916.40" *)
  input [63:0] right;
  wire [63:0] right;
  (* src = "/tmp/domain_clean_chirho.v:917.17-917.20" *)
  output out;
  wire out;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  assign _000_ = ~(right[0] ^ left[0]);
  assign _001_ = right[1] ^ left[1];
  assign _002_ = _000_ & ~(_001_);
  assign _003_ = right[2] ^ left[2];
  assign _004_ = right[3] ^ left[3];
  assign _005_ = _004_ | _003_;
  assign _006_ = _002_ & ~(_005_);
  assign _007_ = right[4] ^ left[4];
  assign _008_ = right[5] ^ left[5];
  assign _009_ = _008_ | _007_;
  assign _010_ = right[6] ^ left[6];
  assign _011_ = right[7] ^ left[7];
  assign _012_ = _011_ | _010_;
  assign _013_ = _012_ | _009_;
  assign _014_ = _006_ & ~(_013_);
  assign _015_ = right[8] ^ left[8];
  assign _016_ = right[9] ^ left[9];
  assign _017_ = _016_ | _015_;
  assign _018_ = right[10] ^ left[10];
  assign _019_ = right[11] ^ left[11];
  assign _020_ = _019_ | _018_;
  assign _021_ = _020_ | _017_;
  assign _022_ = right[12] ^ left[12];
  assign _023_ = right[13] ^ left[13];
  assign _024_ = _023_ | _022_;
  assign _025_ = right[14] ^ left[14];
  assign _026_ = right[15] ^ left[15];
  assign _027_ = _026_ | _025_;
  assign _028_ = _027_ | _024_;
  assign _029_ = _028_ | _021_;
  assign _030_ = _014_ & ~(_029_);
  assign _031_ = right[16] ^ left[16];
  assign _032_ = right[17] ^ left[17];
  assign _033_ = _032_ | _031_;
  assign _034_ = right[18] ^ left[18];
  assign _035_ = right[19] ^ left[19];
  assign _036_ = _035_ | _034_;
  assign _037_ = _036_ | _033_;
  assign _038_ = right[20] ^ left[20];
  assign _039_ = right[21] ^ left[21];
  assign _040_ = _039_ | _038_;
  assign _041_ = right[22] ^ left[22];
  assign _042_ = right[23] ^ left[23];
  assign _043_ = _042_ | _041_;
  assign _044_ = _043_ | _040_;
  assign _045_ = _044_ | _037_;
  assign _046_ = right[24] ^ left[24];
  assign _047_ = right[25] ^ left[25];
  assign _048_ = _047_ | _046_;
  assign _049_ = right[26] ^ left[26];
  assign _050_ = right[27] ^ left[27];
  assign _051_ = _050_ | _049_;
  assign _052_ = _051_ | _048_;
  assign _053_ = right[28] ^ left[28];
  assign _054_ = right[29] ^ left[29];
  assign _055_ = _054_ | _053_;
  assign _056_ = right[30] ^ left[30];
  assign _057_ = right[31] ^ left[31];
  assign _058_ = _057_ | _056_;
  assign _059_ = _058_ | _055_;
  assign _060_ = _059_ | _052_;
  assign _061_ = _060_ | _045_;
  assign _062_ = _030_ & ~(_061_);
  assign _063_ = right[32] ^ left[32];
  assign _064_ = right[33] ^ left[33];
  assign _065_ = _064_ | _063_;
  assign _066_ = right[34] ^ left[34];
  assign _067_ = right[35] ^ left[35];
  assign _068_ = _067_ | _066_;
  assign _069_ = _068_ | _065_;
  assign _070_ = right[36] ^ left[36];
  assign _071_ = right[37] ^ left[37];
  assign _072_ = _071_ | _070_;
  assign _073_ = right[38] ^ left[38];
  assign _074_ = right[39] ^ left[39];
  assign _075_ = _074_ | _073_;
  assign _076_ = _075_ | _072_;
  assign _077_ = _076_ | _069_;
  assign _078_ = right[40] ^ left[40];
  assign _079_ = right[41] ^ left[41];
  assign _080_ = _079_ | _078_;
  assign _081_ = right[42] ^ left[42];
  assign _082_ = right[43] ^ left[43];
  assign _083_ = _082_ | _081_;
  assign _084_ = _083_ | _080_;
  assign _085_ = right[44] ^ left[44];
  assign _086_ = right[45] ^ left[45];
  assign _087_ = _086_ | _085_;
  assign _088_ = right[46] ^ left[46];
  assign _089_ = right[47] ^ left[47];
  assign _090_ = _089_ | _088_;
  assign _091_ = _090_ | _087_;
  assign _092_ = _091_ | _084_;
  assign _093_ = _092_ | _077_;
  assign _094_ = right[48] ^ left[48];
  assign _095_ = right[49] ^ left[49];
  assign _096_ = _095_ | _094_;
  assign _097_ = right[50] ^ left[50];
  assign _098_ = right[51] ^ left[51];
  assign _099_ = _098_ | _097_;
  assign _100_ = _099_ | _096_;
  assign _101_ = right[52] ^ left[52];
  assign _102_ = right[53] ^ left[53];
  assign _103_ = _102_ | _101_;
  assign _104_ = right[54] ^ left[54];
  assign _105_ = right[55] ^ left[55];
  assign _106_ = _105_ | _104_;
  assign _107_ = _106_ | _103_;
  assign _108_ = _107_ | _100_;
  assign _109_ = right[56] ^ left[56];
  assign _110_ = right[57] ^ left[57];
  assign _111_ = _110_ | _109_;
  assign _112_ = right[58] ^ left[58];
  assign _113_ = right[59] ^ left[59];
  assign _114_ = _113_ | _112_;
  assign _115_ = _114_ | _111_;
  assign _116_ = right[60] ^ left[60];
  assign _117_ = right[61] ^ left[61];
  assign _118_ = _117_ | _116_;
  assign _119_ = right[62] ^ left[62];
  assign _120_ = right[63] ^ left[63];
  assign _121_ = _120_ | _119_;
  assign _122_ = _121_ | _118_;
  assign _123_ = _122_ | _115_;
  assign _124_ = _123_ | _108_;
  assign _125_ = _124_ | _093_;
  assign out = _062_ & ~(_125_);
endmodule

(* dynports =  1  *)
(* hdlname = "std_reg" *)
(* src = "/tmp/domain_clean_chirho.v:1261.1-1280.10" *)
module \$paramod\std_reg\WIDTH=s32'00000000000000000000000000000001 (in, write_en, clk, reset, out, done);
  (* src = "/tmp/domain_clean_chirho.v:1264.28-1264.30" *)
  input [0:0] in;
  wire [0:0] in;
  (* src = "/tmp/domain_clean_chirho.v:1265.16-1265.24" *)
  input write_en;
  wire write_en;
  (* src = "/tmp/domain_clean_chirho.v:1266.16-1266.19" *)
  input clk;
  wire clk;
  (* src = "/tmp/domain_clean_chirho.v:1267.16-1267.21" *)
  input reset;
  wire reset;
  (* src = "/tmp/domain_clean_chirho.v:1268.29-1268.32" *)
  output [0:0] out;
  reg [0:0] out;
  (* src = "/tmp/domain_clean_chirho.v:1269.17-1269.21" *)
  output done;
  reg done;
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out <= 1'h0;
    else if (write_en) out <= in;
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) done <= 1'h0;
    else done <= write_en;
endmodule

(* dynports =  1  *)
(* hdlname = "std_reg" *)
(* src = "/tmp/domain_clean_chirho.v:1261.1-1280.10" *)
module \$paramod\std_reg\WIDTH=s32'00000000000000000000000000000010 (in, write_en, clk, reset, out, done);
  (* src = "/tmp/domain_clean_chirho.v:1264.28-1264.30" *)
  input [1:0] in;
  wire [1:0] in;
  (* src = "/tmp/domain_clean_chirho.v:1265.16-1265.24" *)
  input write_en;
  wire write_en;
  (* src = "/tmp/domain_clean_chirho.v:1266.16-1266.19" *)
  input clk;
  wire clk;
  (* src = "/tmp/domain_clean_chirho.v:1267.16-1267.21" *)
  input reset;
  wire reset;
  (* src = "/tmp/domain_clean_chirho.v:1268.29-1268.32" *)
  output [1:0] out;
  reg [1:0] out;
  (* src = "/tmp/domain_clean_chirho.v:1269.17-1269.21" *)
  output done;
  reg done;
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[0] <= 1'h0;
    else if (write_en) out[0] <= in[0];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[1] <= 1'h0;
    else if (write_en) out[1] <= in[1];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) done <= 1'h0;
    else done <= write_en;
endmodule

(* dynports =  1  *)
(* hdlname = "std_reg" *)
(* src = "/tmp/domain_clean_chirho.v:1261.1-1280.10" *)
module \$paramod\std_reg\WIDTH=s32'00000000000000000000000001000000 (in, write_en, clk, reset, out, done);
  (* src = "/tmp/domain_clean_chirho.v:1264.28-1264.30" *)
  input [63:0] in;
  wire [63:0] in;
  (* src = "/tmp/domain_clean_chirho.v:1265.16-1265.24" *)
  input write_en;
  wire write_en;
  (* src = "/tmp/domain_clean_chirho.v:1266.16-1266.19" *)
  input clk;
  wire clk;
  (* src = "/tmp/domain_clean_chirho.v:1267.16-1267.21" *)
  input reset;
  wire reset;
  (* src = "/tmp/domain_clean_chirho.v:1268.29-1268.32" *)
  output [63:0] out;
  reg [63:0] out;
  (* src = "/tmp/domain_clean_chirho.v:1269.17-1269.21" *)
  output done;
  reg done;
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[13] <= 1'h0;
    else if (write_en) out[13] <= in[13];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[14] <= 1'h0;
    else if (write_en) out[14] <= in[14];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[15] <= 1'h0;
    else if (write_en) out[15] <= in[15];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[16] <= 1'h0;
    else if (write_en) out[16] <= in[16];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[17] <= 1'h0;
    else if (write_en) out[17] <= in[17];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[18] <= 1'h0;
    else if (write_en) out[18] <= in[18];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[19] <= 1'h0;
    else if (write_en) out[19] <= in[19];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[20] <= 1'h0;
    else if (write_en) out[20] <= in[20];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[21] <= 1'h0;
    else if (write_en) out[21] <= in[21];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[22] <= 1'h0;
    else if (write_en) out[22] <= in[22];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[23] <= 1'h0;
    else if (write_en) out[23] <= in[23];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[24] <= 1'h0;
    else if (write_en) out[24] <= in[24];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[25] <= 1'h0;
    else if (write_en) out[25] <= in[25];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[26] <= 1'h0;
    else if (write_en) out[26] <= in[26];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[27] <= 1'h0;
    else if (write_en) out[27] <= in[27];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[28] <= 1'h0;
    else if (write_en) out[28] <= in[28];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[29] <= 1'h0;
    else if (write_en) out[29] <= in[29];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[30] <= 1'h0;
    else if (write_en) out[30] <= in[30];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[31] <= 1'h0;
    else if (write_en) out[31] <= in[31];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[32] <= 1'h0;
    else if (write_en) out[32] <= in[32];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[33] <= 1'h0;
    else if (write_en) out[33] <= in[33];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[34] <= 1'h0;
    else if (write_en) out[34] <= in[34];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[35] <= 1'h0;
    else if (write_en) out[35] <= in[35];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[36] <= 1'h0;
    else if (write_en) out[36] <= in[36];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[37] <= 1'h0;
    else if (write_en) out[37] <= in[37];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[38] <= 1'h0;
    else if (write_en) out[38] <= in[38];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[39] <= 1'h0;
    else if (write_en) out[39] <= in[39];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[40] <= 1'h0;
    else if (write_en) out[40] <= in[40];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[41] <= 1'h0;
    else if (write_en) out[41] <= in[41];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[42] <= 1'h0;
    else if (write_en) out[42] <= in[42];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[43] <= 1'h0;
    else if (write_en) out[43] <= in[43];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[44] <= 1'h0;
    else if (write_en) out[44] <= in[44];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[45] <= 1'h0;
    else if (write_en) out[45] <= in[45];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[46] <= 1'h0;
    else if (write_en) out[46] <= in[46];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[47] <= 1'h0;
    else if (write_en) out[47] <= in[47];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[48] <= 1'h0;
    else if (write_en) out[48] <= in[48];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[49] <= 1'h0;
    else if (write_en) out[49] <= in[49];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[50] <= 1'h0;
    else if (write_en) out[50] <= in[50];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[51] <= 1'h0;
    else if (write_en) out[51] <= in[51];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[52] <= 1'h0;
    else if (write_en) out[52] <= in[52];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[53] <= 1'h0;
    else if (write_en) out[53] <= in[53];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[54] <= 1'h0;
    else if (write_en) out[54] <= in[54];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[55] <= 1'h0;
    else if (write_en) out[55] <= in[55];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[56] <= 1'h0;
    else if (write_en) out[56] <= in[56];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[57] <= 1'h0;
    else if (write_en) out[57] <= in[57];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[58] <= 1'h0;
    else if (write_en) out[58] <= in[58];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[59] <= 1'h0;
    else if (write_en) out[59] <= in[59];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[60] <= 1'h0;
    else if (write_en) out[60] <= in[60];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[61] <= 1'h0;
    else if (write_en) out[61] <= in[61];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[62] <= 1'h0;
    else if (write_en) out[62] <= in[62];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[63] <= 1'h0;
    else if (write_en) out[63] <= in[63];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) done <= 1'h0;
    else done <= write_en;
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[0] <= 1'h0;
    else if (write_en) out[0] <= in[0];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[1] <= 1'h0;
    else if (write_en) out[1] <= in[1];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[2] <= 1'h0;
    else if (write_en) out[2] <= in[2];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[3] <= 1'h0;
    else if (write_en) out[3] <= in[3];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[4] <= 1'h0;
    else if (write_en) out[4] <= in[4];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[5] <= 1'h0;
    else if (write_en) out[5] <= in[5];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[6] <= 1'h0;
    else if (write_en) out[6] <= in[6];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[7] <= 1'h0;
    else if (write_en) out[7] <= in[7];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[8] <= 1'h0;
    else if (write_en) out[8] <= in[8];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[9] <= 1'h0;
    else if (write_en) out[9] <= in[9];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[10] <= 1'h0;
    else if (write_en) out[10] <= in[10];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[11] <= 1'h0;
    else if (write_en) out[11] <= in[11];
  (* \always_ff  = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:1271.1-1279.6" *)
  always @(posedge clk)
    if (reset) out[12] <= 1'h0;
    else if (write_en) out[12] <= in[12];
endmodule

(* dynports =  1  *)
(* hdlname = "std_wire" *)
(* src = "/tmp/domain_clean_chirho.v:1242.1-1249.10" *)
module \$paramod\std_wire\WIDTH=s32'00000000000000000000000000000001 (in, out);
  (* src = "/tmp/domain_clean_chirho.v:1245.28-1245.30" *)
  input [0:0] in;
  wire [0:0] in;
  (* src = "/tmp/domain_clean_chirho.v:1246.29-1246.32" *)
  output [0:0] out;
  wire [0:0] out;
  assign out = in;
endmodule

(* top =  1  *)
(* src = "/tmp/domain_clean_chirho.v:2664.1-2937.10" *)
module main(go, clk, reset, done);
  (* src = "/tmp/domain_clean_chirho.v:2665.15-2665.17" *)
  input go;
  wire go;
  (* src = "/tmp/domain_clean_chirho.v:2666.15-2666.18" *)
  input clk;
  wire clk;
  (* src = "/tmp/domain_clean_chirho.v:2667.15-2667.20" *)
  input reset;
  wire reset;
  (* src = "/tmp/domain_clean_chirho.v:2668.16-2668.20" *)
  output done;
  wire done;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  (* src = "/tmp/domain_clean_chirho.v:2822.6-2822.13" *)
  wire _guard0;
  (* src = "/tmp/domain_clean_chirho.v:2823.6-2823.13" *)
  wire _guard1;
  (* src = "/tmp/domain_clean_chirho.v:2832.6-2832.14" *)
  wire _guard10;
  (* src = "/tmp/domain_clean_chirho.v:2834.6-2834.14" *)
  wire _guard12;
  (* src = "/tmp/domain_clean_chirho.v:2838.6-2838.14" *)
  wire _guard16;
  (* src = "/tmp/domain_clean_chirho.v:2840.6-2840.14" *)
  wire _guard18;
  (* src = "/tmp/domain_clean_chirho.v:2824.6-2824.13" *)
  wire _guard2;
  (* src = "/tmp/domain_clean_chirho.v:2842.6-2842.14" *)
  wire _guard20;
  (* src = "/tmp/domain_clean_chirho.v:2844.6-2844.14" *)
  wire _guard22;
  (* src = "/tmp/domain_clean_chirho.v:2846.6-2846.14" *)
  wire _guard24;
  (* src = "/tmp/domain_clean_chirho.v:2848.6-2848.14" *)
  wire _guard26;
  (* src = "/tmp/domain_clean_chirho.v:2850.6-2850.14" *)
  wire _guard28;
  (* src = "/tmp/domain_clean_chirho.v:2852.6-2852.14" *)
  wire _guard30;
  (* src = "/tmp/domain_clean_chirho.v:2855.6-2855.14" *)
  wire _guard33;
  (* src = "/tmp/domain_clean_chirho.v:2857.6-2857.14" *)
  wire _guard35;
  (* src = "/tmp/domain_clean_chirho.v:2859.6-2859.14" *)
  wire _guard37;
  (* src = "/tmp/domain_clean_chirho.v:2860.6-2860.14" *)
  wire _guard38;
  (* src = "/tmp/domain_clean_chirho.v:2861.6-2861.14" *)
  wire _guard39;
  (* src = "/tmp/domain_clean_chirho.v:2826.6-2826.13" *)
  wire _guard4;
  (* src = "/tmp/domain_clean_chirho.v:2862.6-2862.14" *)
  wire _guard40;
  (* src = "/tmp/domain_clean_chirho.v:2863.6-2863.14" *)
  wire _guard41;
  (* src = "/tmp/domain_clean_chirho.v:2864.6-2864.14" *)
  wire _guard42;
  (* src = "/tmp/domain_clean_chirho.v:2868.6-2868.14" *)
  wire _guard46;
  (* src = "/tmp/domain_clean_chirho.v:2869.6-2869.14" *)
  wire _guard47;
  (* src = "/tmp/domain_clean_chirho.v:2870.6-2870.14" *)
  wire _guard48;
  (* src = "/tmp/domain_clean_chirho.v:2874.6-2874.14" *)
  wire _guard52;
  (* src = "/tmp/domain_clean_chirho.v:2875.6-2875.14" *)
  wire _guard53;
  (* src = "/tmp/domain_clean_chirho.v:2876.6-2876.14" *)
  wire _guard54;
  (* src = "/tmp/domain_clean_chirho.v:2877.6-2877.14" *)
  wire _guard55;
  (* src = "/tmp/domain_clean_chirho.v:2878.6-2878.14" *)
  wire _guard56;
  (* src = "/tmp/domain_clean_chirho.v:2879.6-2879.14" *)
  wire _guard57;
  (* src = "/tmp/domain_clean_chirho.v:2880.6-2880.14" *)
  wire _guard58;
  (* src = "/tmp/domain_clean_chirho.v:2881.6-2881.14" *)
  wire _guard59;
  (* src = "/tmp/domain_clean_chirho.v:2828.6-2828.13" *)
  wire _guard6;
  (* src = "/tmp/domain_clean_chirho.v:2882.6-2882.14" *)
  wire _guard60;
  (* src = "/tmp/domain_clean_chirho.v:2886.6-2886.14" *)
  wire _guard64;
  (* src = "/tmp/domain_clean_chirho.v:2887.6-2887.14" *)
  wire _guard65;
  (* src = "/tmp/domain_clean_chirho.v:2696.7-2696.14" *)
  wire fsm_clk;
  (* src = "/tmp/domain_clean_chirho.v:2699.7-2699.15" *)
  (* unused_bits = "0" *)
  wire fsm_done;
  (* src = "/tmp/domain_clean_chirho.v:2694.13-2694.19" *)
  wire [1:0] fsm_in;
  (* src = "/tmp/domain_clean_chirho.v:2698.13-2698.20" *)
  wire [1:0] fsm_out;
  (* src = "/tmp/domain_clean_chirho.v:2697.7-2697.16" *)
  wire fsm_reset;
  (* src = "/tmp/domain_clean_chirho.v:2695.7-2695.19" *)
  wire fsm_write_en;
  (* src = "/tmp/domain_clean_chirho.v:2691.14-2691.29" *)
  wire [63:0] full_chirho_out;
  (* src = "/tmp/domain_clean_chirho.v:2702.7-2702.31" *)
  wire init_vars_chirho_done_in;
  (* src = "/tmp/domain_clean_chirho.v:2703.7-2703.32" *)
  wire init_vars_chirho_done_out;
  (* src = "/tmp/domain_clean_chirho.v:2700.7-2700.29" *)
  wire init_vars_chirho_go_in;
  (* src = "/tmp/domain_clean_chirho.v:2701.7-2701.30" *)
  wire init_vars_chirho_go_out;
  (* src = "/tmp/domain_clean_chirho.v:2706.7-2706.22" *)
  wire invoke0_done_in;
  (* src = "/tmp/domain_clean_chirho.v:2707.7-2707.23" *)
  wire invoke0_done_out;
  (* src = "/tmp/domain_clean_chirho.v:2704.7-2704.20" *)
  wire invoke0_go_in;
  (* src = "/tmp/domain_clean_chirho.v:2705.7-2705.21" *)
  wire invoke0_go_out;
  (* src = "/tmp/domain_clean_chirho.v:2710.7-2710.22" *)
  wire invoke1_done_in;
  (* src = "/tmp/domain_clean_chirho.v:2711.7-2711.23" *)
  wire invoke1_done_out;
  (* src = "/tmp/domain_clean_chirho.v:2708.7-2708.20" *)
  wire invoke1_go_in;
  (* src = "/tmp/domain_clean_chirho.v:2709.7-2709.21" *)
  wire invoke1_go_out;
  (* src = "/tmp/domain_clean_chirho.v:2714.7-2714.19" *)
  wire tdcc_done_in;
  (* src = "/tmp/domain_clean_chirho.v:2715.7-2715.20" *)
  wire tdcc_done_out;
  (* src = "/tmp/domain_clean_chirho.v:2712.7-2712.17" *)
  wire tdcc_go_in;
  (* src = "/tmp/domain_clean_chirho.v:2713.7-2713.18" *)
  wire tdcc_go_out;
  (* src = "/tmp/domain_clean_chirho.v:2692.14-2692.30" *)
  wire [63:0] test1_chirho_out;
  (* src = "/tmp/domain_clean_chirho.v:2693.14-2693.30" *)
  wire [63:0] test2_chirho_out;
  (* src = "/tmp/domain_clean_chirho.v:2689.7-2689.23" *)
  wire unify_chirho_clk;
  (* src = "/tmp/domain_clean_chirho.v:2684.14-2684.36" *)
  wire [63:0] unify_chirho_d1_chirho;
  (* src = "/tmp/domain_clean_chirho.v:2685.14-2685.36" *)
  wire [63:0] unify_chirho_d2_chirho;
  (* src = "/tmp/domain_clean_chirho.v:2686.7-2686.24" *)
  wire unify_chirho_done;
  (* src = "/tmp/domain_clean_chirho.v:2688.7-2688.33" *)
  (* unused_bits = "0" *)
  wire unify_chirho_failed_chirho;
  (* src = "/tmp/domain_clean_chirho.v:2683.7-2683.22" *)
  wire unify_chirho_go;
  (* src = "/tmp/domain_clean_chirho.v:2690.7-2690.25" *)
  wire unify_chirho_reset;
  (* src = "/tmp/domain_clean_chirho.v:2687.14-2687.40" *)
  wire [63:0] unify_chirho_result_chirho;
  (* src = "/tmp/domain_clean_chirho.v:2673.7-2673.22" *)
  wire var0_chirho_clk;
  (* src = "/tmp/domain_clean_chirho.v:2676.7-2676.23" *)
  wire var0_chirho_done;
  (* src = "/tmp/domain_clean_chirho.v:2671.14-2671.28" *)
  wire [63:0] var0_chirho_in;
  (* src = "/tmp/domain_clean_chirho.v:2675.14-2675.29" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63" *)
  wire [63:0] var0_chirho_out;
  (* src = "/tmp/domain_clean_chirho.v:2674.7-2674.24" *)
  wire var0_chirho_reset;
  (* src = "/tmp/domain_clean_chirho.v:2672.7-2672.27" *)
  wire var0_chirho_write_en;
  (* src = "/tmp/domain_clean_chirho.v:2679.7-2679.22" *)
  wire var3_chirho_clk;
  (* src = "/tmp/domain_clean_chirho.v:2682.7-2682.23" *)
  wire var3_chirho_done;
  (* src = "/tmp/domain_clean_chirho.v:2677.14-2677.28" *)
  wire [63:0] var3_chirho_in;
  (* src = "/tmp/domain_clean_chirho.v:2681.14-2681.29" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63" *)
  wire [63:0] var3_chirho_out;
  (* src = "/tmp/domain_clean_chirho.v:2680.7-2680.24" *)
  wire var3_chirho_reset;
  (* src = "/tmp/domain_clean_chirho.v:2678.7-2678.27" *)
  wire var3_chirho_write_en;
  assign _guard2 = fsm_out[1] & fsm_out[0];
  assign _000_ = ~_guard2;
  assign _001_ = fsm_out[1] | fsm_out[0];
  assign _002_ = _001_ | ~(_guard22);
  assign _003_ = _guard12 & ~(_002_);
  assign _004_ = _000_ & ~(_003_);
  assign _005_ = fsm_out[1] | ~(fsm_out[0]);
  assign _006_ = _guard10 & ~(_005_);
  assign _007_ = ~(_006_ & _guard12);
  assign _008_ = ~(_007_ & _004_);
  assign _009_ = fsm_out[0] | ~(fsm_out[1]);
  assign _010_ = _009_ | ~(_guard16);
  assign _011_ = _guard12 & ~(_010_);
  assign fsm_write_en = _011_ | _008_;
  assign var0_chirho_write_en = _guard38 | _guard37;
  assign _012_ = _005_ | _guard10;
  assign invoke0_go_in = _guard12 & ~(_012_);
  assign _013_ = _009_ | _guard16;
  assign invoke1_go_in = _guard12 & ~(_013_);
  assign _014_ = _001_ | _guard22;
  assign init_vars_chirho_go_in = _guard12 & ~(_014_);
  assign _015_ = _011_ & ~(_guard2);
  assign fsm_in[0] = _015_ | _003_;
  assign _016_ = _007_ & ~(_011_);
  assign _017_ = _000_ & ~(_016_);
  assign fsm_in[1] = _017_ & ~(_003_);
  assign var0_chirho_in[0] = _guard37 ? full_chirho_out[0] : unify_chirho_result_chirho[0];
  assign var0_chirho_in[1] = _guard37 ? full_chirho_out[1] : unify_chirho_result_chirho[1];
  assign var0_chirho_in[2] = _guard37 ? full_chirho_out[2] : unify_chirho_result_chirho[2];
  assign var0_chirho_in[3] = _guard37 ? full_chirho_out[3] : unify_chirho_result_chirho[3];
  assign var0_chirho_in[4] = _guard37 ? full_chirho_out[4] : unify_chirho_result_chirho[4];
  assign var0_chirho_in[5] = _guard37 ? full_chirho_out[5] : unify_chirho_result_chirho[5];
  assign var0_chirho_in[6] = _guard37 ? full_chirho_out[6] : unify_chirho_result_chirho[6];
  assign var0_chirho_in[7] = _guard37 ? full_chirho_out[7] : unify_chirho_result_chirho[7];
  assign var0_chirho_in[8] = _guard37 ? full_chirho_out[8] : unify_chirho_result_chirho[8];
  assign var0_chirho_in[9] = _guard37 ? full_chirho_out[9] : unify_chirho_result_chirho[9];
  assign var0_chirho_in[10] = _guard37 ? full_chirho_out[10] : unify_chirho_result_chirho[10];
  assign var0_chirho_in[11] = _guard37 ? full_chirho_out[11] : unify_chirho_result_chirho[11];
  assign var0_chirho_in[12] = _guard37 ? full_chirho_out[12] : unify_chirho_result_chirho[12];
  assign var0_chirho_in[13] = _guard37 ? full_chirho_out[13] : unify_chirho_result_chirho[13];
  assign var0_chirho_in[14] = _guard37 ? full_chirho_out[14] : unify_chirho_result_chirho[14];
  assign var0_chirho_in[15] = _guard37 ? full_chirho_out[15] : unify_chirho_result_chirho[15];
  assign var0_chirho_in[16] = _guard37 ? full_chirho_out[16] : unify_chirho_result_chirho[16];
  assign var0_chirho_in[17] = _guard37 ? full_chirho_out[17] : unify_chirho_result_chirho[17];
  assign var0_chirho_in[18] = _guard37 ? full_chirho_out[18] : unify_chirho_result_chirho[18];
  assign var0_chirho_in[19] = _guard37 ? full_chirho_out[19] : unify_chirho_result_chirho[19];
  assign var0_chirho_in[20] = _guard37 ? full_chirho_out[20] : unify_chirho_result_chirho[20];
  assign var0_chirho_in[21] = _guard37 ? full_chirho_out[21] : unify_chirho_result_chirho[21];
  assign var0_chirho_in[22] = _guard37 ? full_chirho_out[22] : unify_chirho_result_chirho[22];
  assign var0_chirho_in[23] = _guard37 ? full_chirho_out[23] : unify_chirho_result_chirho[23];
  assign var0_chirho_in[24] = _guard37 ? full_chirho_out[24] : unify_chirho_result_chirho[24];
  assign var0_chirho_in[25] = _guard37 ? full_chirho_out[25] : unify_chirho_result_chirho[25];
  assign var0_chirho_in[26] = _guard37 ? full_chirho_out[26] : unify_chirho_result_chirho[26];
  assign var0_chirho_in[27] = _guard37 ? full_chirho_out[27] : unify_chirho_result_chirho[27];
  assign var0_chirho_in[28] = _guard37 ? full_chirho_out[28] : unify_chirho_result_chirho[28];
  assign var0_chirho_in[29] = _guard37 ? full_chirho_out[29] : unify_chirho_result_chirho[29];
  assign var0_chirho_in[30] = _guard37 ? full_chirho_out[30] : unify_chirho_result_chirho[30];
  assign var0_chirho_in[31] = _guard37 ? full_chirho_out[31] : unify_chirho_result_chirho[31];
  assign var0_chirho_in[32] = _guard37 ? full_chirho_out[32] : unify_chirho_result_chirho[32];
  assign var0_chirho_in[33] = _guard37 ? full_chirho_out[33] : unify_chirho_result_chirho[33];
  assign var0_chirho_in[34] = _guard37 ? full_chirho_out[34] : unify_chirho_result_chirho[34];
  assign var0_chirho_in[35] = _guard37 ? full_chirho_out[35] : unify_chirho_result_chirho[35];
  assign var0_chirho_in[36] = _guard37 ? full_chirho_out[36] : unify_chirho_result_chirho[36];
  assign var0_chirho_in[37] = _guard37 ? full_chirho_out[37] : unify_chirho_result_chirho[37];
  assign var0_chirho_in[38] = _guard37 ? full_chirho_out[38] : unify_chirho_result_chirho[38];
  assign var0_chirho_in[39] = _guard37 ? full_chirho_out[39] : unify_chirho_result_chirho[39];
  assign var0_chirho_in[40] = _guard37 ? full_chirho_out[40] : unify_chirho_result_chirho[40];
  assign var0_chirho_in[41] = _guard37 ? full_chirho_out[41] : unify_chirho_result_chirho[41];
  assign var0_chirho_in[42] = _guard37 ? full_chirho_out[42] : unify_chirho_result_chirho[42];
  assign var0_chirho_in[43] = _guard37 ? full_chirho_out[43] : unify_chirho_result_chirho[43];
  assign var0_chirho_in[44] = _guard37 ? full_chirho_out[44] : unify_chirho_result_chirho[44];
  assign var0_chirho_in[45] = _guard37 ? full_chirho_out[45] : unify_chirho_result_chirho[45];
  assign var0_chirho_in[46] = _guard37 ? full_chirho_out[46] : unify_chirho_result_chirho[46];
  assign var0_chirho_in[47] = _guard37 ? full_chirho_out[47] : unify_chirho_result_chirho[47];
  assign var0_chirho_in[48] = _guard37 ? full_chirho_out[48] : unify_chirho_result_chirho[48];
  assign var0_chirho_in[49] = _guard37 ? full_chirho_out[49] : unify_chirho_result_chirho[49];
  assign var0_chirho_in[50] = _guard37 ? full_chirho_out[50] : unify_chirho_result_chirho[50];
  assign var0_chirho_in[51] = _guard37 ? full_chirho_out[51] : unify_chirho_result_chirho[51];
  assign var0_chirho_in[52] = _guard37 ? full_chirho_out[52] : unify_chirho_result_chirho[52];
  assign var0_chirho_in[53] = _guard37 ? full_chirho_out[53] : unify_chirho_result_chirho[53];
  assign var0_chirho_in[54] = _guard37 ? full_chirho_out[54] : unify_chirho_result_chirho[54];
  assign var0_chirho_in[55] = _guard37 ? full_chirho_out[55] : unify_chirho_result_chirho[55];
  assign var0_chirho_in[56] = _guard37 ? full_chirho_out[56] : unify_chirho_result_chirho[56];
  assign var0_chirho_in[57] = _guard37 ? full_chirho_out[57] : unify_chirho_result_chirho[57];
  assign var0_chirho_in[58] = _guard37 ? full_chirho_out[58] : unify_chirho_result_chirho[58];
  assign var0_chirho_in[59] = _guard37 ? full_chirho_out[59] : unify_chirho_result_chirho[59];
  assign var0_chirho_in[60] = _guard37 ? full_chirho_out[60] : unify_chirho_result_chirho[60];
  assign var0_chirho_in[61] = _guard37 ? full_chirho_out[61] : unify_chirho_result_chirho[61];
  assign var0_chirho_in[62] = _guard37 ? full_chirho_out[62] : unify_chirho_result_chirho[62];
  assign var0_chirho_in[63] = _guard37 ? full_chirho_out[63] : unify_chirho_result_chirho[63];
  assign unify_chirho_d1_chirho[0] = _guard58 & test1_chirho_out[0];
  assign unify_chirho_d1_chirho[1] = test1_chirho_out[1] & _guard58;
  assign unify_chirho_d1_chirho[2] = test1_chirho_out[2] & _guard58;
  assign unify_chirho_d1_chirho[3] = test1_chirho_out[3] & _guard58;
  assign unify_chirho_d1_chirho[4] = test1_chirho_out[4] & _guard58;
  assign unify_chirho_d1_chirho[5] = test1_chirho_out[5] & _guard58;
  assign unify_chirho_d1_chirho[6] = test1_chirho_out[6] & _guard58;
  assign unify_chirho_d1_chirho[7] = test1_chirho_out[7] & _guard58;
  assign unify_chirho_d1_chirho[8] = test1_chirho_out[8] & _guard58;
  assign unify_chirho_d1_chirho[9] = test1_chirho_out[9] & _guard58;
  assign unify_chirho_d1_chirho[10] = test1_chirho_out[10] & _guard58;
  assign unify_chirho_d1_chirho[11] = test1_chirho_out[11] & _guard58;
  assign unify_chirho_d1_chirho[12] = test1_chirho_out[12] & _guard58;
  assign unify_chirho_d1_chirho[13] = test1_chirho_out[13] & _guard58;
  assign unify_chirho_d1_chirho[14] = test1_chirho_out[14] & _guard58;
  assign unify_chirho_d1_chirho[15] = test1_chirho_out[15] & _guard58;
  assign unify_chirho_d1_chirho[16] = test1_chirho_out[16] & _guard58;
  assign unify_chirho_d1_chirho[17] = test1_chirho_out[17] & _guard58;
  assign unify_chirho_d1_chirho[18] = test1_chirho_out[18] & _guard58;
  assign unify_chirho_d1_chirho[19] = test1_chirho_out[19] & _guard58;
  assign unify_chirho_d1_chirho[20] = test1_chirho_out[20] & _guard58;
  assign unify_chirho_d1_chirho[21] = test1_chirho_out[21] & _guard58;
  assign unify_chirho_d1_chirho[22] = test1_chirho_out[22] & _guard58;
  assign unify_chirho_d1_chirho[23] = test1_chirho_out[23] & _guard58;
  assign unify_chirho_d1_chirho[24] = test1_chirho_out[24] & _guard58;
  assign unify_chirho_d1_chirho[25] = test1_chirho_out[25] & _guard58;
  assign unify_chirho_d1_chirho[26] = test1_chirho_out[26] & _guard58;
  assign unify_chirho_d1_chirho[27] = test1_chirho_out[27] & _guard58;
  assign unify_chirho_d1_chirho[28] = test1_chirho_out[28] & _guard58;
  assign unify_chirho_d1_chirho[29] = test1_chirho_out[29] & _guard58;
  assign unify_chirho_d1_chirho[30] = test1_chirho_out[30] & _guard58;
  assign unify_chirho_d1_chirho[31] = test1_chirho_out[31] & _guard58;
  assign unify_chirho_d1_chirho[32] = test1_chirho_out[32] & _guard58;
  assign unify_chirho_d1_chirho[33] = test1_chirho_out[33] & _guard58;
  assign unify_chirho_d1_chirho[34] = test1_chirho_out[34] & _guard58;
  assign unify_chirho_d1_chirho[35] = test1_chirho_out[35] & _guard58;
  assign unify_chirho_d1_chirho[36] = test1_chirho_out[36] & _guard58;
  assign unify_chirho_d1_chirho[37] = test1_chirho_out[37] & _guard58;
  assign unify_chirho_d1_chirho[38] = test1_chirho_out[38] & _guard58;
  assign unify_chirho_d1_chirho[39] = test1_chirho_out[39] & _guard58;
  assign unify_chirho_d1_chirho[40] = test1_chirho_out[40] & _guard58;
  assign unify_chirho_d1_chirho[41] = test1_chirho_out[41] & _guard58;
  assign unify_chirho_d1_chirho[42] = test1_chirho_out[42] & _guard58;
  assign unify_chirho_d1_chirho[43] = test1_chirho_out[43] & _guard58;
  assign unify_chirho_d1_chirho[44] = test1_chirho_out[44] & _guard58;
  assign unify_chirho_d1_chirho[45] = test1_chirho_out[45] & _guard58;
  assign unify_chirho_d1_chirho[46] = test1_chirho_out[46] & _guard58;
  assign unify_chirho_d1_chirho[47] = test1_chirho_out[47] & _guard58;
  assign unify_chirho_d1_chirho[48] = test1_chirho_out[48] & _guard58;
  assign unify_chirho_d1_chirho[49] = test1_chirho_out[49] & _guard58;
  assign unify_chirho_d1_chirho[50] = test1_chirho_out[50] & _guard58;
  assign unify_chirho_d1_chirho[51] = test1_chirho_out[51] & _guard58;
  assign unify_chirho_d1_chirho[52] = test1_chirho_out[52] & _guard58;
  assign unify_chirho_d1_chirho[53] = test1_chirho_out[53] & _guard58;
  assign unify_chirho_d1_chirho[54] = test1_chirho_out[54] & _guard58;
  assign unify_chirho_d1_chirho[55] = test1_chirho_out[55] & _guard58;
  assign unify_chirho_d1_chirho[56] = test1_chirho_out[56] & _guard58;
  assign unify_chirho_d1_chirho[57] = test1_chirho_out[57] & _guard58;
  assign unify_chirho_d1_chirho[58] = test1_chirho_out[58] & _guard58;
  assign unify_chirho_d1_chirho[59] = test1_chirho_out[59] & _guard58;
  assign unify_chirho_d1_chirho[60] = test1_chirho_out[60] & _guard58;
  assign unify_chirho_d1_chirho[61] = test1_chirho_out[61] & _guard58;
  assign unify_chirho_d1_chirho[62] = test1_chirho_out[62] & _guard58;
  assign unify_chirho_d1_chirho[63] = test1_chirho_out[63] & _guard58;
  assign unify_chirho_d2_chirho[0] = test2_chirho_out[0] & _guard58;
  assign unify_chirho_d2_chirho[1] = test2_chirho_out[1] & _guard58;
  assign unify_chirho_d2_chirho[2] = test2_chirho_out[2] & _guard58;
  assign unify_chirho_d2_chirho[3] = test2_chirho_out[3] & _guard58;
  assign unify_chirho_d2_chirho[4] = test2_chirho_out[4] & _guard58;
  assign unify_chirho_d2_chirho[5] = test2_chirho_out[5] & _guard58;
  assign unify_chirho_d2_chirho[6] = test2_chirho_out[6] & _guard58;
  assign unify_chirho_d2_chirho[7] = test2_chirho_out[7] & _guard58;
  assign unify_chirho_d2_chirho[8] = test2_chirho_out[8] & _guard58;
  assign unify_chirho_d2_chirho[9] = test2_chirho_out[9] & _guard58;
  assign unify_chirho_d2_chirho[10] = test2_chirho_out[10] & _guard58;
  assign unify_chirho_d2_chirho[11] = test2_chirho_out[11] & _guard58;
  assign unify_chirho_d2_chirho[12] = test2_chirho_out[12] & _guard58;
  assign unify_chirho_d2_chirho[13] = test2_chirho_out[13] & _guard58;
  assign unify_chirho_d2_chirho[14] = test2_chirho_out[14] & _guard58;
  assign unify_chirho_d2_chirho[15] = test2_chirho_out[15] & _guard58;
  assign unify_chirho_d2_chirho[16] = test2_chirho_out[16] & _guard58;
  assign unify_chirho_d2_chirho[17] = test2_chirho_out[17] & _guard58;
  assign unify_chirho_d2_chirho[18] = test2_chirho_out[18] & _guard58;
  assign unify_chirho_d2_chirho[19] = test2_chirho_out[19] & _guard58;
  assign unify_chirho_d2_chirho[20] = test2_chirho_out[20] & _guard58;
  assign unify_chirho_d2_chirho[21] = test2_chirho_out[21] & _guard58;
  assign unify_chirho_d2_chirho[22] = test2_chirho_out[22] & _guard58;
  assign unify_chirho_d2_chirho[23] = test2_chirho_out[23] & _guard58;
  assign unify_chirho_d2_chirho[24] = test2_chirho_out[24] & _guard58;
  assign unify_chirho_d2_chirho[25] = test2_chirho_out[25] & _guard58;
  assign unify_chirho_d2_chirho[26] = test2_chirho_out[26] & _guard58;
  assign unify_chirho_d2_chirho[27] = test2_chirho_out[27] & _guard58;
  assign unify_chirho_d2_chirho[28] = test2_chirho_out[28] & _guard58;
  assign unify_chirho_d2_chirho[29] = test2_chirho_out[29] & _guard58;
  assign unify_chirho_d2_chirho[30] = test2_chirho_out[30] & _guard58;
  assign unify_chirho_d2_chirho[31] = test2_chirho_out[31] & _guard58;
  assign unify_chirho_d2_chirho[32] = test2_chirho_out[32] & _guard58;
  assign unify_chirho_d2_chirho[33] = test2_chirho_out[33] & _guard58;
  assign unify_chirho_d2_chirho[34] = test2_chirho_out[34] & _guard58;
  assign unify_chirho_d2_chirho[35] = test2_chirho_out[35] & _guard58;
  assign unify_chirho_d2_chirho[36] = test2_chirho_out[36] & _guard58;
  assign unify_chirho_d2_chirho[37] = test2_chirho_out[37] & _guard58;
  assign unify_chirho_d2_chirho[38] = test2_chirho_out[38] & _guard58;
  assign unify_chirho_d2_chirho[39] = test2_chirho_out[39] & _guard58;
  assign unify_chirho_d2_chirho[40] = test2_chirho_out[40] & _guard58;
  assign unify_chirho_d2_chirho[41] = test2_chirho_out[41] & _guard58;
  assign unify_chirho_d2_chirho[42] = test2_chirho_out[42] & _guard58;
  assign unify_chirho_d2_chirho[43] = test2_chirho_out[43] & _guard58;
  assign unify_chirho_d2_chirho[44] = test2_chirho_out[44] & _guard58;
  assign unify_chirho_d2_chirho[45] = test2_chirho_out[45] & _guard58;
  assign unify_chirho_d2_chirho[46] = test2_chirho_out[46] & _guard58;
  assign unify_chirho_d2_chirho[47] = test2_chirho_out[47] & _guard58;
  assign unify_chirho_d2_chirho[48] = test2_chirho_out[48] & _guard58;
  assign unify_chirho_d2_chirho[49] = test2_chirho_out[49] & _guard58;
  assign unify_chirho_d2_chirho[50] = test2_chirho_out[50] & _guard58;
  assign unify_chirho_d2_chirho[51] = test2_chirho_out[51] & _guard58;
  assign unify_chirho_d2_chirho[52] = test2_chirho_out[52] & _guard58;
  assign unify_chirho_d2_chirho[53] = test2_chirho_out[53] & _guard58;
  assign unify_chirho_d2_chirho[54] = test2_chirho_out[54] & _guard58;
  assign unify_chirho_d2_chirho[55] = test2_chirho_out[55] & _guard58;
  assign unify_chirho_d2_chirho[56] = test2_chirho_out[56] & _guard58;
  assign unify_chirho_d2_chirho[57] = test2_chirho_out[57] & _guard58;
  assign unify_chirho_d2_chirho[58] = test2_chirho_out[58] & _guard58;
  assign unify_chirho_d2_chirho[59] = test2_chirho_out[59] & _guard58;
  assign unify_chirho_d2_chirho[60] = test2_chirho_out[60] & _guard58;
  assign unify_chirho_d2_chirho[61] = test2_chirho_out[61] & _guard58;
  assign unify_chirho_d2_chirho[62] = test2_chirho_out[62] & _guard58;
  assign unify_chirho_d2_chirho[63] = test2_chirho_out[63] & _guard58;
  (* src = "/tmp/domain_clean_chirho.v:2766.3-2773.2" *)
  \$paramod\std_reg\WIDTH=s32'00000000000000000000000000000010  fsm (
    .clk(clk),
    .done(fsm_done),
    .in(fsm_in),
    .out(fsm_out),
    .reset(reset),
    .write_en(fsm_write_en)
  );
  (* src = "/tmp/domain_clean_chirho.v:2749.3-2751.2" *)
  \$paramod$671ddf9215aeccc75d9ce31d476d82165dd4dc10\std_const  full_chirho (
    .out(full_chirho_out)
  );
  (* src = "/tmp/domain_clean_chirho.v:2782.3-2785.2" *)
  \$paramod\std_wire\WIDTH=s32'00000000000000000000000000000001  init_vars_chirho_done (
    .in(init_vars_chirho_done_in),
    .out(_guard22)
  );
  (* src = "/tmp/domain_clean_chirho.v:2776.3-2779.2" *)
  \$paramod\std_wire\WIDTH=s32'00000000000000000000000000000001  init_vars_chirho_go (
    .in(init_vars_chirho_go_in),
    .out(_guard37)
  );
  (* src = "/tmp/domain_clean_chirho.v:2794.3-2797.2" *)
  \$paramod\std_wire\WIDTH=s32'00000000000000000000000000000001  invoke0_done (
    .in(invoke0_done_in),
    .out(_guard10)
  );
  (* src = "/tmp/domain_clean_chirho.v:2788.3-2791.2" *)
  \$paramod\std_wire\WIDTH=s32'00000000000000000000000000000001  invoke0_go (
    .in(invoke0_go_in),
    .out(_guard58)
  );
  (* src = "/tmp/domain_clean_chirho.v:2806.3-2809.2" *)
  \$paramod\std_wire\WIDTH=s32'00000000000000000000000000000001  invoke1_done (
    .in(invoke1_done_in),
    .out(_guard16)
  );
  (* src = "/tmp/domain_clean_chirho.v:2800.3-2803.2" *)
  \$paramod\std_wire\WIDTH=s32'00000000000000000000000000000001  invoke1_go (
    .in(invoke1_go_in),
    .out(_guard38)
  );
  (* src = "/tmp/domain_clean_chirho.v:2818.3-2821.2" *)
  \$paramod\std_wire\WIDTH=s32'00000000000000000000000000000001  tdcc_done (
    .in(_guard2),
    .out(tdcc_done_out)
  );
  (* src = "/tmp/domain_clean_chirho.v:2812.3-2815.2" *)
  \$paramod\std_wire\WIDTH=s32'00000000000000000000000000000001  tdcc_go (
    .in(go),
    .out(_guard12)
  );
  (* src = "/tmp/domain_clean_chirho.v:2755.3-2757.2" *)
  \$paramod$25c94d4f8057fb6df438ef354e0c89df8651fe3a\std_const  test1_chirho (
    .out(test1_chirho_out)
  );
  (* src = "/tmp/domain_clean_chirho.v:2761.3-2763.2" *)
  \$paramod$48af5e9059f5cb939f41deb7ac38ebaea4b9f561\std_const  test2_chirho (
    .out(test2_chirho_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/tmp/domain_clean_chirho.v:2736.19-2745.2" *)
  unify_unit_chirho unify_chirho (
    .clk(clk),
    .d1_chirho(unify_chirho_d1_chirho),
    .d2_chirho(unify_chirho_d2_chirho),
    .done(invoke0_done_in),
    .failed_chirho(unify_chirho_failed_chirho),
    .go(_guard58),
    .reset(reset),
    .result_chirho(unify_chirho_result_chirho)
  );
  (* src = "/tmp/domain_clean_chirho.v:2718.3-2725.2" *)
  \$paramod\std_reg\WIDTH=s32'00000000000000000000000001000000  var0_chirho (
    .clk(clk),
    .done(invoke1_done_in),
    .in(var0_chirho_in),
    .out(var0_chirho_out),
    .reset(reset),
    .write_en(var0_chirho_write_en)
  );
  (* src = "/tmp/domain_clean_chirho.v:2728.3-2735.2" *)
  \$paramod\std_reg\WIDTH=s32'00000000000000000000000001000000  var3_chirho (
    .clk(clk),
    .done(init_vars_chirho_done_in),
    .in(full_chirho_out),
    .out(var3_chirho_out),
    .reset(reset),
    .write_en(_guard37)
  );
  assign _guard0 = 1'h1;
  assign _guard1 = tdcc_done_out;
  assign _guard18 = _guard12;
  assign _guard20 = fsm_write_en;
  assign _guard24 = _guard12;
  assign _guard26 = _guard2;
  assign _guard28 = _guard16;
  assign _guard30 = _guard12;
  assign _guard33 = _guard10;
  assign _guard35 = _guard12;
  assign _guard39 = var0_chirho_write_en;
  assign _guard4 = _guard22;
  assign _guard40 = _guard37;
  assign _guard41 = _guard38;
  assign _guard42 = _guard10;
  assign _guard46 = _guard12;
  assign _guard47 = invoke0_go_in;
  assign _guard48 = _guard16;
  assign _guard52 = _guard12;
  assign _guard53 = invoke1_go_in;
  assign _guard54 = _guard37;
  assign _guard55 = _guard37;
  assign _guard56 = _guard2;
  assign _guard57 = _guard58;
  assign _guard59 = _guard58;
  assign _guard6 = _guard12;
  assign _guard60 = _guard22;
  assign _guard64 = _guard12;
  assign _guard65 = init_vars_chirho_go_in;
  assign done = tdcc_done_out;
  assign fsm_clk = clk;
  assign fsm_reset = reset;
  assign init_vars_chirho_done_out = _guard22;
  assign init_vars_chirho_go_out = _guard37;
  assign invoke0_done_out = _guard10;
  assign invoke0_go_out = _guard58;
  assign invoke1_done_out = _guard16;
  assign invoke1_go_out = _guard38;
  assign tdcc_done_in = _guard2;
  assign tdcc_go_in = go;
  assign tdcc_go_out = _guard12;
  assign unify_chirho_clk = clk;
  assign unify_chirho_done = invoke0_done_in;
  assign unify_chirho_go = _guard58;
  assign unify_chirho_reset = reset;
  assign var0_chirho_clk = clk;
  assign var0_chirho_done = invoke1_done_in;
  assign var0_chirho_reset = reset;
  assign var3_chirho_clk = clk;
  assign var3_chirho_done = init_vars_chirho_done_in;
  assign var3_chirho_in = full_chirho_out;
  assign var3_chirho_reset = reset;
  assign var3_chirho_write_en = _guard37;
endmodule

(* src = "/tmp/domain_clean_chirho.v:1282.1-1498.10" *)
module unify_unit_chirho(go, d1_chirho, d2_chirho, done, result_chirho, failed_chirho, clk, reset);
  (* src = "/tmp/domain_clean_chirho.v:1283.15-1283.17" *)
  input go;
  wire go;
  (* src = "/tmp/domain_clean_chirho.v:1284.22-1284.31" *)
  input [63:0] d1_chirho;
  wire [63:0] d1_chirho;
  (* src = "/tmp/domain_clean_chirho.v:1285.22-1285.31" *)
  input [63:0] d2_chirho;
  wire [63:0] d2_chirho;
  (* src = "/tmp/domain_clean_chirho.v:1286.16-1286.20" *)
  output done;
  wire done;
  (* src = "/tmp/domain_clean_chirho.v:1287.23-1287.36" *)
  output [63:0] result_chirho;
  wire [63:0] result_chirho;
  (* src = "/tmp/domain_clean_chirho.v:1288.16-1288.29" *)
  output failed_chirho;
  wire failed_chirho;
  (* src = "/tmp/domain_clean_chirho.v:1289.15-1289.18" *)
  input clk;
  wire clk;
  (* src = "/tmp/domain_clean_chirho.v:1290.15-1290.20" *)
  input reset;
  wire reset;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* src = "/tmp/domain_clean_chirho.v:1416.6-1416.13" *)
  wire _guard0;
  (* src = "/tmp/domain_clean_chirho.v:1417.6-1417.13" *)
  wire _guard1;
  (* src = "/tmp/domain_clean_chirho.v:1426.6-1426.14" *)
  wire _guard10;
  (* src = "/tmp/domain_clean_chirho.v:1427.6-1427.14" *)
  wire _guard11;
  (* src = "/tmp/domain_clean_chirho.v:1430.6-1430.14" *)
  wire _guard14;
  (* src = "/tmp/domain_clean_chirho.v:1432.6-1432.14" *)
  wire _guard16;
  (* src = "/tmp/domain_clean_chirho.v:1434.6-1434.14" *)
  wire _guard18;
  (* src = "/tmp/domain_clean_chirho.v:1418.6-1418.13" *)
  wire _guard2;
  (* src = "/tmp/domain_clean_chirho.v:1436.6-1436.14" *)
  wire _guard20;
  (* src = "/tmp/domain_clean_chirho.v:1438.6-1438.14" *)
  wire _guard22;
  (* src = "/tmp/domain_clean_chirho.v:1439.6-1439.14" *)
  wire _guard23;
  (* src = "/tmp/domain_clean_chirho.v:1440.6-1440.14" *)
  wire _guard24;
  (* src = "/tmp/domain_clean_chirho.v:1442.6-1442.14" *)
  wire _guard26;
  (* src = "/tmp/domain_clean_chirho.v:1444.6-1444.14" *)
  wire _guard28;
  (* src = "/tmp/domain_clean_chirho.v:1419.6-1419.13" *)
  wire _guard3;
  (* src = "/tmp/domain_clean_chirho.v:1446.6-1446.14" *)
  wire _guard30;
  (* src = "/tmp/domain_clean_chirho.v:1447.6-1447.14" *)
  wire _guard31;
  (* src = "/tmp/domain_clean_chirho.v:1448.6-1448.14" *)
  wire _guard32;
  (* src = "/tmp/domain_clean_chirho.v:1449.6-1449.14" *)
  wire _guard33;
  (* src = "/tmp/domain_clean_chirho.v:1450.6-1450.14" *)
  wire _guard34;
  (* src = "/tmp/domain_clean_chirho.v:1454.6-1454.14" *)
  wire _guard38;
  (* src = "/tmp/domain_clean_chirho.v:1455.6-1455.14" *)
  wire _guard39;
  (* src = "/tmp/domain_clean_chirho.v:1420.6-1420.13" *)
  wire _guard4;
  (* src = "/tmp/domain_clean_chirho.v:1456.6-1456.14" *)
  wire _guard40;
  (* src = "/tmp/domain_clean_chirho.v:1460.6-1460.14" *)
  wire _guard44;
  (* src = "/tmp/domain_clean_chirho.v:1461.6-1461.14" *)
  wire _guard45;
  (* src = "/tmp/domain_clean_chirho.v:1462.6-1462.14" *)
  wire _guard46;
  (* src = "/tmp/domain_clean_chirho.v:1421.6-1421.13" *)
  wire _guard5;
  (* src = "/tmp/domain_clean_chirho.v:1422.6-1422.13" *)
  wire _guard6;
  (* src = "/tmp/domain_clean_chirho.v:1424.6-1424.13" *)
  wire _guard8;
  (* src = "/tmp/domain_clean_chirho.v:1299.14-1299.34" *)
  wire [63:0] and_gate_chirho_left;
  (* src = "/tmp/domain_clean_chirho.v:1301.14-1301.33" *)
  wire [63:0] and_gate_chirho_out;
  (* src = "/tmp/domain_clean_chirho.v:1300.14-1300.35" *)
  wire [63:0] and_gate_chirho_right;
  (* src = "/tmp/domain_clean_chirho.v:1303.14-1303.28" *)
  wire [63:0] eq_chirho_left;
  (* src = "/tmp/domain_clean_chirho.v:1305.7-1305.20" *)
  wire eq_chirho_out;
  (* src = "/tmp/domain_clean_chirho.v:1304.14-1304.29" *)
  wire [63:0] eq_chirho_right;
  (* src = "/tmp/domain_clean_chirho.v:1308.7-1308.28" *)
  wire failed_reg_chirho_clk;
  (* src = "/tmp/domain_clean_chirho.v:1311.7-1311.29" *)
  wire failed_reg_chirho_done;
  (* src = "/tmp/domain_clean_chirho.v:1306.7-1306.27" *)
  wire failed_reg_chirho_in;
  (* src = "/tmp/domain_clean_chirho.v:1310.7-1310.28" *)
  wire failed_reg_chirho_out;
  (* src = "/tmp/domain_clean_chirho.v:1309.7-1309.30" *)
  wire failed_reg_chirho_reset;
  (* src = "/tmp/domain_clean_chirho.v:1307.7-1307.33" *)
  wire failed_reg_chirho_write_en;
  (* src = "/tmp/domain_clean_chirho.v:1314.7-1314.14" *)
  wire fsm_clk;
  (* src = "/tmp/domain_clean_chirho.v:1317.7-1317.15" *)
  (* unused_bits = "0" *)
  wire fsm_done;
  (* src = "/tmp/domain_clean_chirho.v:1312.13-1312.19" *)
  wire [1:0] fsm_in;
  (* src = "/tmp/domain_clean_chirho.v:1316.13-1316.20" *)
  wire [1:0] fsm_out;
  (* src = "/tmp/domain_clean_chirho.v:1315.7-1315.16" *)
  wire fsm_reset;
  (* src = "/tmp/domain_clean_chirho.v:1313.7-1313.19" *)
  wire fsm_write_en;
  (* src = "/tmp/domain_clean_chirho.v:1320.7-1320.22" *)
  wire invoke0_done_in;
  (* src = "/tmp/domain_clean_chirho.v:1321.7-1321.23" *)
  wire invoke0_done_out;
  (* src = "/tmp/domain_clean_chirho.v:1318.7-1318.20" *)
  wire invoke0_go_in;
  (* src = "/tmp/domain_clean_chirho.v:1319.7-1319.21" *)
  wire invoke0_go_out;
  (* src = "/tmp/domain_clean_chirho.v:1324.7-1324.22" *)
  wire invoke1_done_in;
  (* src = "/tmp/domain_clean_chirho.v:1325.7-1325.23" *)
  wire invoke1_done_out;
  (* src = "/tmp/domain_clean_chirho.v:1322.7-1322.20" *)
  wire invoke1_go_in;
  (* src = "/tmp/domain_clean_chirho.v:1323.7-1323.21" *)
  wire invoke1_go_out;
  (* src = "/tmp/domain_clean_chirho.v:1295.7-1295.28" *)
  wire result_reg_chirho_clk;
  (* src = "/tmp/domain_clean_chirho.v:1298.7-1298.29" *)
  wire result_reg_chirho_done;
  (* src = "/tmp/domain_clean_chirho.v:1293.14-1293.34" *)
  wire [63:0] result_reg_chirho_in;
  (* src = "/tmp/domain_clean_chirho.v:1297.14-1297.35" *)
  wire [63:0] result_reg_chirho_out;
  (* src = "/tmp/domain_clean_chirho.v:1296.7-1296.30" *)
  wire result_reg_chirho_reset;
  (* src = "/tmp/domain_clean_chirho.v:1294.7-1294.33" *)
  wire result_reg_chirho_write_en;
  (* src = "/tmp/domain_clean_chirho.v:1328.7-1328.19" *)
  wire tdcc_done_in;
  (* src = "/tmp/domain_clean_chirho.v:1329.7-1329.20" *)
  wire tdcc_done_out;
  (* src = "/tmp/domain_clean_chirho.v:1326.7-1326.17" *)
  wire tdcc_go_in;
  (* src = "/tmp/domain_clean_chirho.v:1327.7-1327.18" *)
  wire tdcc_go_out;
  (* src = "/tmp/domain_clean_chirho.v:1302.14-1302.29" *)
  wire [63:0] zero_chirho_out;
  assign _00_ = fsm_out[1] | fsm_out[0];
  assign _01_ = _00_ | ~(_guard20);
  assign _guard11 = _guard10 & ~(_01_);
  assign _guard24 = fsm_out[1] & ~(fsm_out[0]);
  assign _02_ = ~(_guard24 | _guard11);
  assign _03_ = fsm_out[1] | ~(fsm_out[0]);
  assign _04_ = _03_ | ~(_guard14);
  assign _05_ = _04_ | ~(_guard10);
  assign fsm_write_en = ~(_05_ & _02_);
  assign _06_ = _00_ | _guard20;
  assign invoke0_go_in = _guard10 & ~(_06_);
  assign _07_ = _03_ | _guard14;
  assign invoke1_go_in = _guard10 & ~(_07_);
  assign _08_ = _05_ | _guard24;
  assign fsm_in[1] = ~(_08_ | _guard11);
  (* src = "/tmp/domain_clean_chirho.v:1342.3-1346.2" *)
  \$paramod\std_and\WIDTH=s32'00000000000000000000000001000000  and_gate_chirho (
    .left(d1_chirho),
    .out(and_gate_chirho_out),
    .right(d2_chirho)
  );
  (* src = "/tmp/domain_clean_chirho.v:1355.3-1359.2" *)
  \$paramod\std_eq\WIDTH=s32'00000000000000000000000001000000  eq_chirho (
    .left(eq_chirho_left),
    .out(eq_chirho_out),
    .right(eq_chirho_right)
  );
  (* src = "/tmp/domain_clean_chirho.v:1362.3-1369.2" *)
  \$paramod\std_reg\WIDTH=s32'00000000000000000000000000000001  failed_reg_chirho (
    .clk(clk),
    .done(failed_reg_chirho_done),
    .in(eq_chirho_out),
    .out(failed_reg_chirho_out),
    .reset(reset),
    .write_en(failed_reg_chirho_write_en)
  );
  (* src = "/tmp/domain_clean_chirho.v:1372.3-1379.2" *)
  \$paramod\std_reg\WIDTH=s32'00000000000000000000000000000010  fsm (
    .clk(clk),
    .done(fsm_done),
    .in({ fsm_in[1], _guard11 }),
    .out(fsm_out),
    .reset(reset),
    .write_en(fsm_write_en)
  );
  (* src = "/tmp/domain_clean_chirho.v:1388.3-1391.2" *)
  \$paramod\std_wire\WIDTH=s32'00000000000000000000000000000001  invoke0_done (
    .in(invoke0_done_in),
    .out(_guard20)
  );
  (* src = "/tmp/domain_clean_chirho.v:1382.3-1385.2" *)
  \$paramod\std_wire\WIDTH=s32'00000000000000000000000000000001  invoke0_go (
    .in(invoke0_go_in),
    .out(invoke0_go_out)
  );
  (* src = "/tmp/domain_clean_chirho.v:1400.3-1403.2" *)
  \$paramod\std_wire\WIDTH=s32'00000000000000000000000000000001  invoke1_done (
    .in(failed_reg_chirho_done),
    .out(_guard14)
  );
  (* src = "/tmp/domain_clean_chirho.v:1394.3-1397.2" *)
  \$paramod\std_wire\WIDTH=s32'00000000000000000000000000000001  invoke1_go (
    .in(invoke1_go_in),
    .out(failed_reg_chirho_write_en)
  );
  (* src = "/tmp/domain_clean_chirho.v:1332.3-1339.2" *)
  \$paramod\std_reg\WIDTH=s32'00000000000000000000000001000000  result_reg_chirho (
    .clk(clk),
    .done(invoke0_done_in),
    .in(and_gate_chirho_out),
    .out(eq_chirho_left),
    .reset(reset),
    .write_en(invoke0_go_out)
  );
  (* src = "/tmp/domain_clean_chirho.v:1412.3-1415.2" *)
  \$paramod\std_wire\WIDTH=s32'00000000000000000000000000000001  tdcc_done (
    .in(_guard24),
    .out(tdcc_done_out)
  );
  (* src = "/tmp/domain_clean_chirho.v:1406.3-1409.2" *)
  \$paramod\std_wire\WIDTH=s32'00000000000000000000000000000001  tdcc_go (
    .in(go),
    .out(_guard10)
  );
  (* src = "/tmp/domain_clean_chirho.v:1350.3-1352.2" *)
  \$paramod$b7c52f579af5ece61583054911856cac9593fccf\std_const  zero_chirho (
    .out(eq_chirho_right)
  );
  assign _guard0 = 1'h1;
  assign _guard1 = invoke0_go_out;
  assign _guard16 = _guard10;
  assign _guard18 = fsm_write_en;
  assign _guard2 = invoke0_go_out;
  assign _guard22 = _guard10;
  assign _guard23 = _guard11;
  assign _guard26 = _guard14;
  assign _guard28 = _guard10;
  assign _guard3 = failed_reg_chirho_write_en;
  assign _guard30 = invoke0_go_out;
  assign _guard31 = invoke0_go_out;
  assign _guard32 = failed_reg_chirho_write_en;
  assign _guard33 = failed_reg_chirho_write_en;
  assign _guard34 = _guard20;
  assign _guard38 = _guard10;
  assign _guard39 = invoke0_go_in;
  assign _guard4 = failed_reg_chirho_write_en;
  assign _guard40 = _guard14;
  assign _guard44 = _guard10;
  assign _guard45 = invoke1_go_in;
  assign _guard46 = _guard24;
  assign _guard5 = tdcc_done_out;
  assign _guard6 = _guard24;
  assign _guard8 = _guard20;
  assign and_gate_chirho_left = d1_chirho;
  assign and_gate_chirho_right = d2_chirho;
  assign done = tdcc_done_out;
  assign failed_chirho = failed_reg_chirho_out;
  assign failed_reg_chirho_clk = clk;
  assign failed_reg_chirho_in = eq_chirho_out;
  assign failed_reg_chirho_reset = reset;
  assign fsm_clk = clk;
  assign fsm_in[0] = _guard11;
  assign fsm_reset = reset;
  assign invoke0_done_out = _guard20;
  assign invoke1_done_in = failed_reg_chirho_done;
  assign invoke1_done_out = _guard14;
  assign invoke1_go_out = failed_reg_chirho_write_en;
  assign result_chirho = eq_chirho_left;
  assign result_reg_chirho_clk = clk;
  assign result_reg_chirho_done = invoke0_done_in;
  assign result_reg_chirho_in = and_gate_chirho_out;
  assign result_reg_chirho_out = eq_chirho_left;
  assign result_reg_chirho_reset = reset;
  assign result_reg_chirho_write_en = invoke0_go_out;
  assign tdcc_done_in = _guard24;
  assign tdcc_go_in = go;
  assign tdcc_go_out = _guard10;
  assign zero_chirho_out = eq_chirho_right;
endmodule
