/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.4. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module diffTrainChirho
    ( // Inputs
      input wire  clk // clock
    , input wire  rst // reset
    , input wire  en_chirho // enable
    , input wire [127:0] cmd_chirho

      // Outputs
    , output wire [63:0] resp_chirho
    );
  wire [0:0] c$diffTrainTopChirho_$j_arg3;
  wire [0:0] c$diffTrainTopChirho_$j_$j1_arg3;
  // DiffTrainChirho.hs:292:1-18
  wire signed [63:0] c$ds_app_arg;
  wire signed [63:0] res;
  wire signed [63:0] result;
  wire signed [63:0] c$case_alt;
  wire signed [31:0] result_0;
  wire signed [31:0] c$case_alt_0;
  wire signed [31:0] c$case_alt_1;
  wire signed [31:0] c$case_alt_2;
  wire signed [64:0] c$app_arg;
  wire signed [64:0] shiftedR;
  wire signed [64:0] ds;
  wire signed [31:0] result_1;
  wire signed [31:0] c$case_alt_3;
  wire [16:0] c$app_arg_0;
  wire [15:0] c$app_arg_1;
  wire [15:0] rL;
  wire [47:0] rR;
  wire [63:0] ds3;
  wire signed [63:0] c$ds3_app_arg;
  wire signed [31:0] result_2;
  wire signed [31:0] c$case_alt_4;
  wire [31:0] \r' ;
  wire [32:0] \c$r'_app_arg ;
  wire signed [32:0] r;
  // DiffTrainChirho.hs:292:1-18
  wire [214:0] c$ds_case_alt;
  // DiffTrainChirho.hs:292:1-18
  wire [214:0] c$ds_case_alt_0;
  // DiffTrainChirho.hs:292:1-18
  wire [214:0] c$ds_case_alt_1;
  // DiffTrainChirho.hs:292:1-18
  reg [214:0] c$ds_case_alt_2;
  // DiffTrainChirho.hs:(377,1)-(380,31)
  reg [146:0] fsm_chirho = {3'd0,   16'd0,   16'd0,   16'd0,   32'b00010110001100010110001100010110,
 32'sd131072,   32'sd0};
  wire [49:0] resp_chirho_2;
  wire [15:0] c$bv;
  wire [49:0] resp_chirho_11;
  wire [49:0] c$diffTrainTopChirho_$j_arg3_selection_0;
  wire [49:0] c$diffTrainTopChirho_$j_$j1_arg3_selection_0;
  wire [15:0] c$i_4;
  wire signed [31:0] c$s;
  wire [47:0] c$bv_0;
  wire [47:0] c$bv_1;
  wire [31:0] c$bv_2;
  wire [31:0] c$bv_3;
  wire [32:0] \r'_projection ;
  wire [2:0] c$ds_case_alt_selection_6;

  assign resp_chirho_2 = {c$ds_case_alt_2[66:66],
                          c$ds_case_alt_2[67:67],
                          $signed(c$ds_case_alt_2[31:0]),
                          fsm_chirho[143:128]};

  assign c$bv = ((resp_chirho_2[15:0]));

  assign resp_chirho_11 = {c$ds_case_alt_2[66:66],
                           c$ds_case_alt_2[67:67],
                           $signed(c$ds_case_alt_2[31:0]),
                           fsm_chirho[143:128]};

  assign resp_chirho = {16'b0000000000000000,({({({c$diffTrainTopChirho_$j_arg3,c$diffTrainTopChirho_$j_$j1_arg3}),(c$bv[0+:14])}),(($unsigned($signed(resp_chirho_11[47:16]))))})};

  assign c$diffTrainTopChirho_$j_arg3_selection_0 = {c$ds_case_alt_2[66:66],
                                                     c$ds_case_alt_2[67:67],
                                                     $signed(c$ds_case_alt_2[31:0]),
                                                     fsm_chirho[143:128]};

  assign c$diffTrainTopChirho_$j_arg3 = c$diffTrainTopChirho_$j_arg3_selection_0[49:49] ? 1'b1 : 1'b0;

  assign c$diffTrainTopChirho_$j_$j1_arg3_selection_0 = {c$ds_case_alt_2[66:66],
                                                         c$ds_case_alt_2[67:67],
                                                         $signed(c$ds_case_alt_2[31:0]),
                                                         fsm_chirho[143:128]};

  assign c$diffTrainTopChirho_$j_$j1_arg3 = c$diffTrainTopChirho_$j_$j1_arg3_selection_0[48:48] ? 1'b1 : 1'b0;

  assign c$i_4 = fsm_chirho[143:128];

  assign c$ds_app_arg = $unsigned({{(64-16) {1'b0}},c$i_4});

  assign res = c$ds_app_arg <<< 64'd16;

  assign result = (res > 64'sd2147483647) ? 64'sd2147483647 : c$case_alt;

  assign c$case_alt = (res < -64'sd2147483648) ? -64'sd2147483648 : res;

  assign result_0 = (ds >= 65'sd0) ? c$case_alt_0 : c$case_alt_1;

  assign c$case_alt_0 = (c$app_arg == 65'sd0) ? c$case_alt_2 : 32'sd2147483647;

  assign c$case_alt_1 = (c$app_arg == -65'sd2147483648) ? c$case_alt_2 : -32'sd2147483648;

  assign c$case_alt_2 = $signed({shiftedR[65-1],shiftedR[0+:(32-1)]});

  assign c$app_arg = shiftedR & -65'sd2147483648;

  assign shiftedR = ds >>> (64'sd16);

  assign c$s = ($signed(result[0+:32]) );

  assign ds = (($signed({{(65-32) {c$s[32-1]}},c$s})) <<< (64'sd32)) / 65'sd32768000;

  assign c$bv_0 = (rR >> (64'sd16));

  assign result_1 = (((~ (| (c$app_arg_0))) | (& (c$app_arg_0))) == 1'b1) ? ($signed((c$bv_0[0+:32]))) : c$case_alt_3;

  assign c$case_alt_3 = (( c$app_arg_1[16-1] ) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

  assign c$bv_1 = (rR);

  assign c$app_arg_0 = ({((( c$bv_1[48-1] ))),c$app_arg_1});

  assign c$app_arg_1 = rL;

  assign rL = ds3[63:48];

  assign rR = ds3[47:0];

  assign ds3 = (($unsigned(c$ds3_app_arg)));

  assign c$ds3_app_arg = result_0 * -32'sd127796;

  assign c$bv_2 = (\r' );

  assign result_2 = ((( \c$r'_app_arg [33-1] ) ^ ( c$bv_2[32-1] )) == 1'b0) ? ($signed(\r' )) : c$case_alt_4;

  assign c$bv_3 = (($unsigned(result_1)));

  assign c$case_alt_4 = ((1'b0 & ( c$bv_3[32-1] )) == 1'b0) ? 32'sd2147483647 : -32'sd2147483648;

  assign \r'_projection  = \c$r'_app_arg ;

  assign \r'  = \r'_projection [31:0];

  assign \c$r'_app_arg  = ($unsigned(r));

  assign r = 32'sd131072 + result_1;

  assign c$ds_case_alt = (fsm_chirho[127:112] >= 16'd50) ? {{3'd5,
                                                             fsm_chirho[143:128],   fsm_chirho[127:112],
                                                             fsm_chirho[111:96],   fsm_chirho[95:64],
                                                             $signed(fsm_chirho[63:32]),
                                                             $signed(fsm_chirho[31:0])},   {1'b0,   1'b1,
                                                                                            1'b0,   1'b0,   32'd0,
                                                                                            32'sd0}} : {{3'd3,
                                                                                                         fsm_chirho[143:128],
                                                                                                         fsm_chirho[127:112],
                                                                                                         16'd0,
                                                                                                         fsm_chirho[95:64],
                                                                                                         $signed(fsm_chirho[63:32]),
                                                                                                         $signed(fsm_chirho[31:0])},
                                                                                                        {1'b0,   1'b1,
                                                                                                         1'b0,   1'b0,
                                                                                                         32'd0,
                                                                                                         32'sd0}};

  assign c$ds_case_alt_0 = (fsm_chirho[111:96] >= 16'd300) ? {{3'd4,
                                                               fsm_chirho[143:128],   fsm_chirho[127:112],
                                                               fsm_chirho[111:96],   fsm_chirho[95:64],
                                                               $signed(fsm_chirho[63:32]),
                                                               $signed(fsm_chirho[31:0])},   {1'b0,   1'b1,
                                                                                              1'b0,   1'b0,   32'd0,
                                                                                              32'sd0}} : {{3'd3,
                                                                                                           fsm_chirho[143:128],
                                                                                                           fsm_chirho[127:112],
                                                                                                           fsm_chirho[111:96] + 16'd1,
                                                                                                           fsm_chirho[95:64],
                                                                                                           $signed(fsm_chirho[63:32]),
                                                                                                           $signed(fsm_chirho[31:0])},
                                                                                                          {1'b0,
                                                                                                           1'b1,
                                                                                                           1'b0,
                                                                                                           1'b0,
                                                                                                           32'd0,
                                                                                                           32'sd0}};

  assign c$ds_case_alt_1 = (fsm_chirho[143:128] >= 16'd500) ? {{3'd6,
                                                                fsm_chirho[143:128],   fsm_chirho[127:112],
                                                                fsm_chirho[111:96],   fsm_chirho[95:64],
                                                                $signed(fsm_chirho[63:32]),
                                                                $signed(fsm_chirho[31:0])},   {1'b0,   1'b1,
                                                                                               1'b0,   1'b1,   32'd0,
                                                                                               32'sd0}} : {{3'd2,
                                                                                                            fsm_chirho[143:128] + 16'd1,
                                                                                                            16'd0,
                                                                                                            fsm_chirho[111:96],
                                                                                                            fsm_chirho[95:64],
                                                                                                            result_2,
                                                                                                            $signed(fsm_chirho[31:0])},
                                                                                                           {1'b0,
                                                                                                            1'b1,
                                                                                                            1'b0,
                                                                                                            1'b0,
                                                                                                            32'd0,
                                                                                                            32'sd0}};

  assign c$ds_case_alt_selection_6 = fsm_chirho[146:144];

  always @(*) begin
    case(c$ds_case_alt_selection_6)
      3'b000 : c$ds_case_alt_2 = {fsm_chirho,
                                  {1'b0,   1'b0,   1'b0,   1'b0,   32'd0,
                                   32'sd0}};
      3'b001 : c$ds_case_alt_2 = {{3'd2,
                                   fsm_chirho[143:128],   16'd0,
                                   fsm_chirho[111:96],   fsm_chirho[95:64],
                                   $signed(fsm_chirho[63:32]),
                                   $signed(fsm_chirho[31:0])},   {1'b0,   1'b1,
                                                                  1'b0,   1'b0,   32'd0,   32'sd0}};
      3'b010 : c$ds_case_alt_2 = c$ds_case_alt;
      3'b011 : c$ds_case_alt_2 = c$ds_case_alt_0;
      3'b100 : c$ds_case_alt_2 = {{3'd2,
                                   fsm_chirho[143:128],
                                   fsm_chirho[127:112] + 16'd1,
                                   fsm_chirho[111:96],   fsm_chirho[95:64],
                                   $signed(fsm_chirho[63:32]),
                                   $signed(fsm_chirho[31:0])},   {1'b0,   1'b1,
                                                                  1'b0,   1'b0,   32'd0,   32'sd0}};
      3'b101 : c$ds_case_alt_2 = c$ds_case_alt_1;
      3'b110 : c$ds_case_alt_2 = {{3'd7,
                                   fsm_chirho[143:128],   fsm_chirho[127:112],
                                   fsm_chirho[111:96],   fsm_chirho[95:64],
                                   $signed(fsm_chirho[63:32]),
                                   $signed(fsm_chirho[31:0])},   {1'b0,   1'b1,
                                                                  1'b0,   1'b0,   32'd0,   32'sd0}};
      default : c$ds_case_alt_2 = {{3'd0,
                                    fsm_chirho[143:128],   fsm_chirho[127:112],
                                    fsm_chirho[111:96],   fsm_chirho[95:64],
                                    $signed(fsm_chirho[63:32]),
                                    $signed(fsm_chirho[31:0])},   {1'b1,   1'b0,
                                                                   1'b0,   1'b0,   32'd0,
                                                                   $signed(fsm_chirho[31:0])}};
    endcase
  end

  // register begin
  always @(posedge clk or  posedge  rst) begin : fsm_chirho_register
    if ( rst) begin
      fsm_chirho <= {3'd0,   16'd0,   16'd0,   16'd0,   32'b00010110001100010110001100010110,
   32'sd131072,   32'sd0};
    end else if (en_chirho) begin
      fsm_chirho <= c$ds_case_alt_2[214:68];
    end
  end
  // register end


endmodule

