/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.4. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module searchEngine64BitChirho
    ( // Inputs
      input wire  clk // clock
    , input wire  rst // reset
    , input wire  enChirho // enable
    , input wire [69:0] cmdChirho

      // Outputs
    , output wire [513:0] respChirho
    );
  // MiniKanrenChirho.hs:285:1-23
  reg [9796:0] c$ds_app_arg = {{64'b1111111111111111111111111111111111111111111111111111111111111111,
  64'b1111111111111111111111111111111111111111111111111111111111111111,
  64'b1111111111111111111111111111111111111111111111111111111111111111,
  64'b1111111111111111111111111111111111111111111111111111111111111111,
  64'b1111111111111111111111111111111111111111111111111111111111111111,
  64'b1111111111111111111111111111111111111111111111111111111111111111,
  64'b1111111111111111111111111111111111111111111111111111111111111111,
  64'b1111111111111111111111111111111111111111111111111111111111111111},
 1'b1,
 {{1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
  {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
  {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
  {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
  {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
  {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
  {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
  {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
  {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
  {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
  {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
  {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
  {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
  {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
  {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
  {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}},
 4'd0};
  wire  c$case_alt;
  wire [7:0] c$app_arg;
  // MiniKanrenChirho.hs:200:1-16
  reg [9796:0] \stChirho' ;
  // MiniKanrenChirho.hs:200:1-16
  wire [9796:0] \c$stChirho'_case_alt ;
  wire [9796:0] result;
  // MiniKanrenChirho.hs:200:1-16
  wire [511:0] \c$stChirho'_case_alt_0 ;
  // MiniKanrenChirho.hs:200:1-16
  wire [578:0] eChirho;
  // MiniKanrenChirho.hs:200:1-16
  wire [579:0] \c$stChirho'_case_scrut ;
  // MiniKanrenChirho.hs:200:1-16
  wire [3:0] newSPChirho;
  // MiniKanrenChirho.hs:200:1-16
  wire [9279:0] \c$stChirho'_app_arg ;
  // MiniKanrenChirho.hs:200:1-16
  wire [511:0] \c$stChirho'_app_arg_0 ;
  // MiniKanrenChirho.hs:200:1-16
  wire [63:0] ds4;
  // MiniKanrenChirho.hs:200:1-16
  wire [63:0] xChirho;
  // MiniKanrenChirho.hs:200:1-16
  wire signed [63:0] c$xChirho_app_arg;
  // MiniKanrenChirho.hs:200:1-16
  wire [2:0] vChirho;
  // MiniKanrenChirho.hs:200:1-16
  wire [511:0] \c$stChirho'_app_arg_1 ;
  // MiniKanrenChirho.hs:200:1-16
  wire [63:0] resultChirho;
  // MiniKanrenChirho.hs:200:1-16
  wire [63:0] maskChirho;
  // MiniKanrenChirho.hs:200:1-16
  wire [63:0] c$resultChirho_app_arg;
  // MiniKanrenChirho.hs:200:1-16
  wire signed [63:0] c$resultChirho_app_arg_0;
  // MiniKanrenChirho.hs:200:1-16
  wire [2:0] vChirho_0;
  // MiniKanrenChirho.hs:200:1-16
  wire [3:0] engSPChirho1;
  // MiniKanrenChirho.hs:200:1-16
  wire [9279:0] engStackChirho1;
  // MiniKanrenChirho.hs:200:1-16
  wire [511:0] \c$stChirho'_app_arg_2 ;
  // MiniKanrenChirho.hs:200:1-16
  reg [63:0] \c$stChirho'_case_alt_1 ;
  // MiniKanrenChirho.hs:200:1-16
  reg [63:0] \c$stChirho'_case_alt_2 ;
  // MiniKanrenChirho.hs:200:1-16
  reg [63:0] \c$stChirho'_case_alt_3 ;
  // MiniKanrenChirho.hs:200:1-16
  reg [63:0] \c$stChirho'_case_alt_4 ;
  // MiniKanrenChirho.hs:200:1-16
  reg [63:0] \c$stChirho'_case_alt_5 ;
  // MiniKanrenChirho.hs:200:1-16
  reg [63:0] \c$stChirho'_case_alt_6 ;
  // MiniKanrenChirho.hs:200:1-16
  reg [63:0] \c$stChirho'_case_alt_7 ;
  // MiniKanrenChirho.hs:200:1-16
  reg [63:0] \c$stChirho'_case_alt_8 ;
  // MiniKanrenChirho.hs:200:1-16
  wire [63:0] resultChirho_0;
  // MiniKanrenChirho.hs:200:1-16
  wire [63:0] c$resultChirho_app_arg_1;
  // MiniKanrenChirho.hs:200:1-16
  wire [63:0] c$resultChirho_app_arg_2;
  // MiniKanrenChirho.hs:200:1-16
  wire signed [63:0] c$resultChirho_app_arg_3;
  // MiniKanrenChirho.hs:200:1-16
  wire [2:0] v1Chirho;
  // MiniKanrenChirho.hs:200:1-16
  wire signed [63:0] \c$stChirho'_case_scrut_0 ;
  // MiniKanrenChirho.hs:200:1-16
  wire [2:0] v2Chirho;
  wire [10310:0] c$ds_app_arg_1;
  wire [10310:0] respChirho_projection;
  wire [511:0] c$vec;
  wire [2:0] c$i_28;
  wire [511:0] c$vec_0;
  wire [511:0] c$vec_1;
  wire [511:0] c$vecFlat;
  wire [511:0] c$vec_2;
  wire [511:0] c$vecFlat_0;
  wire [511:0] c$vec_3;
  wire signed [63:0] \c$stChirho'_case_alt_selection_2 ;
  wire signed [63:0] \c$stChirho'_case_alt_selection_5 ;
  wire signed [63:0] \c$stChirho'_case_alt_selection_8 ;
  wire signed [63:0] \c$stChirho'_case_alt_selection_11 ;
  wire signed [63:0] \c$stChirho'_case_alt_selection_14 ;
  wire signed [63:0] \c$stChirho'_case_alt_selection_17 ;
  wire signed [63:0] \c$stChirho'_case_alt_selection_20 ;
  wire signed [63:0] \c$stChirho'_case_alt_selection_23 ;
  wire [511:0] c$vecFlat_1;
  wire [511:0] c$vecFlat_2;

  assign c$ds_app_arg_1 = {\stChirho' ,
                           {\stChirho' [9284:9284],
                            \stChirho' [9284:9284] & c$case_alt,
                            \stChirho' [9796:9285]}};

  // register begin
  always @(posedge clk or  posedge  rst) begin : c$ds_app_arg_register
    if ( rst) begin
      c$ds_app_arg <= {{64'b1111111111111111111111111111111111111111111111111111111111111111,
    64'b1111111111111111111111111111111111111111111111111111111111111111,
    64'b1111111111111111111111111111111111111111111111111111111111111111,
    64'b1111111111111111111111111111111111111111111111111111111111111111,
    64'b1111111111111111111111111111111111111111111111111111111111111111,
    64'b1111111111111111111111111111111111111111111111111111111111111111,
    64'b1111111111111111111111111111111111111111111111111111111111111111,
    64'b1111111111111111111111111111111111111111111111111111111111111111},
   1'b1,
   {{1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
    {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
    {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
    {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
    {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
    {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
    {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
    {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
    {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
    {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
    {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
    {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
    {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
    {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
    {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
    {1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}},
   4'd0};
    end else if (enChirho) begin
      c$ds_app_arg <= c$ds_app_arg_1[10310:514];
    end
  end
  // register end

  assign respChirho_projection = {\stChirho' ,
                                  {\stChirho' [9284:9284],
                                   \stChirho' [9284:9284] & c$case_alt,
                                   \stChirho' [9796:9285]}};

  assign respChirho = respChirho_projection[513:0];

  wire [7:0] vec;
  wire  acc_3_0;
  wire  acc_1;
  wire  acc_2;
  wire  acc_3;
  wire  acc_4;
  wire  acc_5;
  wire  acc_6;
  wire  acc_7;
  wire  acc_8;
  wire  acc_1_0;
  wire  acc_1_1;
  wire  acc_1_2;
  wire  acc_1_3;
  wire  acc_2_0;
  wire  acc_2_1;
  assign c$case_alt = acc_3_0;

  assign vec = c$app_arg;

  assign acc_1 = vec[7:7];

  assign acc_2 = vec[6:6];

  assign acc_3 = vec[5:5];

  assign acc_4 = vec[4:4];

  assign acc_5 = vec[3:3];

  assign acc_6 = vec[2:2];

  assign acc_7 = vec[1:1];

  assign acc_8 = vec[0:0];

  assign acc_1_0 = acc_1 & acc_2;



  assign acc_1_1 = acc_3 & acc_4;



  assign acc_1_2 = acc_5 & acc_6;



  assign acc_1_3 = acc_7 & acc_8;



  assign acc_2_0 = acc_1_0 & acc_1_1;



  assign acc_2_1 = acc_1_2 & acc_1_3;



  assign acc_3_0 = acc_2_0 & acc_2_1;





  assign c$vec = \stChirho' [9796:9285];

  // map begin
  genvar i;
  generate
  for (i=0; i < 8; i = i + 1) begin : map
    wire [63:0] map_in;
    assign map_in = c$vec[i*64+:64];
    wire  map_out;
    assign map_out = (map_in != 64'b0000000000000000000000000000000000000000000000000000000000000000) & ((map_in & (map_in - 64'b0000000000000000000000000000000000000000000000000000000000000001)) == 64'b0000000000000000000000000000000000000000000000000000000000000000);


    assign c$app_arg[i*1+:1] = map_out;
  end
  endgenerate
  // map end

  always @(*) begin
    case(cmdChirho[69:67])
      3'b000 : \stChirho'  = {{8 {64'b1111111111111111111111111111111111111111111111111111111111111111}},
                              1'b1,
                              {16 {{1'b0,579'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}},
                              4'd0};
      3'b001 : \stChirho'  = {\c$stChirho'_app_arg_2 ,
                              c$ds_app_arg[9284:9284] & (~ (resultChirho_0 == 64'b0000000000000000000000000000000000000000000000000000000000000000)),
                              engStackChirho1,   engSPChirho1};
      3'b010 : \stChirho'  = {\c$stChirho'_app_arg_1 ,
                              c$ds_app_arg[9284:9284] & (~ (resultChirho == 64'b0000000000000000000000000000000000000000000000000000000000000000)),
                              engStackChirho1,   engSPChirho1};
      3'b011 : \stChirho'  = {\c$stChirho'_app_arg_0 ,
                              c$ds_app_arg[9284:9284] & (~ (ds4 == 64'b0000000000000000000000000000000000000000000000000000000000000000)),
                              \c$stChirho'_app_arg ,   engSPChirho1 + 4'd1};
      3'b100 : \stChirho'  = \c$stChirho'_case_alt ;
      default : \stChirho'  = c$ds_app_arg;
    endcase
  end

  assign \c$stChirho'_case_alt  = (engSPChirho1 == 4'd0) ? {c$ds_app_arg[9796:9285],
                                                            1'b0,   engStackChirho1,
                                                            engSPChirho1} : result;

  assign result = \c$stChirho'_case_scrut [579:579] ? {\c$stChirho'_case_alt_0 ,
                                                       ~ (eChirho[575:512] == 64'b0000000000000000000000000000000000000000000000000000000000000000),
                                                       engStackChirho1,
                                                       newSPChirho} : {c$ds_app_arg[9796:9285],
                                                                       1'b0,   engStackChirho1,   engSPChirho1};

  assign c$i_28 = eChirho[578:576];

  assign c$vec_0 = eChirho[511:0];

  // vector replace begin
  genvar i_0;
  generate
  for (i_0=0;i_0<8;i_0=i_0+1) begin : vector_replace
    assign \c$stChirho'_case_alt_0 [(7-i_0)*64+:64] = ($unsigned({{(64-3) {1'b0}},c$i_28})) == i_0 ? eChirho[575:512] : c$vec_0[(7-i_0)*64+:64];
  end
  endgenerate
  // vector replace end

  assign eChirho = \c$stChirho'_case_scrut [578:0];

  // index begin
  wire [579:0] vecArray [0:16-1];
  genvar i_1;
  generate
  for (i_1=0; i_1 < 16; i_1=i_1+1) begin : mk_array
    assign vecArray[(16-1)-i_1] = engStackChirho1[i_1*580+:580];
  end
  endgenerate
  assign \c$stChirho'_case_scrut  = vecArray[($unsigned({{(64-4) {1'b0}},newSPChirho}))];
  // index end

  assign newSPChirho = engSPChirho1 - 4'd1;

  // vector replace begin
  genvar i_2;
  generate
  for (i_2=0;i_2<16;i_2=i_2+1) begin : vector_replace_0
    assign \c$stChirho'_app_arg [(15-i_2)*580+:580] = ($unsigned({{(64-4) {1'b0}},engSPChirho1})) == i_2 ? {1'b1,{vChirho,
         xChirho & (xChirho - 64'b0000000000000000000000000000000000000000000000000000000000000001),
         c$ds_app_arg[9796:9285]}} : engStackChirho1[(15-i_2)*580+:580];
  end
  endgenerate
  // vector replace end

  assign c$vec_1 = c$ds_app_arg[9796:9285];

  // vector replace begin
  genvar i_3;
  generate
  for (i_3=0;i_3<8;i_3=i_3+1) begin : vector_replace_1
    assign \c$stChirho'_app_arg_0 [(7-i_3)*64+:64] = c$xChirho_app_arg == i_3 ? ds4 : c$vec_1[(7-i_3)*64+:64];
  end
  endgenerate
  // vector replace end

  assign ds4 = xChirho & (-xChirho);

  assign c$vecFlat = c$ds_app_arg[9796:9285];

  // index begin
  wire [63:0] vecArray_0 [0:8-1];
  genvar i_4;
  generate
  for (i_4=0; i_4 < 8; i_4=i_4+1) begin : mk_array_0
    assign vecArray_0[(8-1)-i_4] = c$vecFlat[i_4*64+:64];
  end
  endgenerate
  assign xChirho = vecArray_0[c$xChirho_app_arg];
  // index end

  assign c$xChirho_app_arg = $unsigned({{(64-3) {1'b0}},vChirho});

  assign vChirho = cmdChirho[66:64];

  assign c$vec_2 = c$ds_app_arg[9796:9285];

  // vector replace begin
  genvar i_5;
  generate
  for (i_5=0;i_5<8;i_5=i_5+1) begin : vector_replace_2
    assign \c$stChirho'_app_arg_1 [(7-i_5)*64+:64] = c$resultChirho_app_arg_0 == i_5 ? resultChirho : c$vec_2[(7-i_5)*64+:64];
  end
  endgenerate
  // vector replace end

  assign resultChirho = c$resultChirho_app_arg & maskChirho;

  assign maskChirho = cmdChirho[63:0];

  assign c$vecFlat_0 = c$ds_app_arg[9796:9285];

  // index begin
  wire [63:0] vecArray_1 [0:8-1];
  genvar i_6;
  generate
  for (i_6=0; i_6 < 8; i_6=i_6+1) begin : mk_array_1
    assign vecArray_1[(8-1)-i_6] = c$vecFlat_0[i_6*64+:64];
  end
  endgenerate
  assign c$resultChirho_app_arg = vecArray_1[c$resultChirho_app_arg_0];
  // index end

  assign c$resultChirho_app_arg_0 = $unsigned({{(64-3) {1'b0}},vChirho_0});

  assign vChirho_0 = cmdChirho[66:64];

  assign engSPChirho1 = c$ds_app_arg[3:0];

  assign engStackChirho1 = c$ds_app_arg[9283:4];

  assign c$vec_3 = {\c$stChirho'_case_alt_8 ,
                    \c$stChirho'_case_alt_7 ,
                    \c$stChirho'_case_alt_6 ,
                    \c$stChirho'_case_alt_5 ,
                    \c$stChirho'_case_alt_4 ,
                    \c$stChirho'_case_alt_3 ,
                    \c$stChirho'_case_alt_2 ,
                    \c$stChirho'_case_alt_1 };

  // vector replace begin
  genvar i_7;
  generate
  for (i_7=0;i_7<8;i_7=i_7+1) begin : vector_replace_3
    assign \c$stChirho'_app_arg_2 [(7-i_7)*64+:64] = c$resultChirho_app_arg_3 == i_7 ? resultChirho_0 : c$vec_3[(7-i_7)*64+:64];
  end
  endgenerate
  // vector replace end

  assign \c$stChirho'_case_alt_selection_2  = \c$stChirho'_case_scrut_0 ;

  always @(*) begin
    case(\c$stChirho'_case_alt_selection_2 )
      64'sd7 : \c$stChirho'_case_alt_1  = resultChirho_0;
      default : \c$stChirho'_case_alt_1  = c$ds_app_arg[9348:9285];
    endcase
  end

  assign \c$stChirho'_case_alt_selection_5  = \c$stChirho'_case_scrut_0 ;

  always @(*) begin
    case(\c$stChirho'_case_alt_selection_5 )
      64'sd6 : \c$stChirho'_case_alt_2  = resultChirho_0;
      default : \c$stChirho'_case_alt_2  = c$ds_app_arg[9412:9349];
    endcase
  end

  assign \c$stChirho'_case_alt_selection_8  = \c$stChirho'_case_scrut_0 ;

  always @(*) begin
    case(\c$stChirho'_case_alt_selection_8 )
      64'sd5 : \c$stChirho'_case_alt_3  = resultChirho_0;
      default : \c$stChirho'_case_alt_3  = c$ds_app_arg[9476:9413];
    endcase
  end

  assign \c$stChirho'_case_alt_selection_11  = \c$stChirho'_case_scrut_0 ;

  always @(*) begin
    case(\c$stChirho'_case_alt_selection_11 )
      64'sd4 : \c$stChirho'_case_alt_4  = resultChirho_0;
      default : \c$stChirho'_case_alt_4  = c$ds_app_arg[9540:9477];
    endcase
  end

  assign \c$stChirho'_case_alt_selection_14  = \c$stChirho'_case_scrut_0 ;

  always @(*) begin
    case(\c$stChirho'_case_alt_selection_14 )
      64'sd3 : \c$stChirho'_case_alt_5  = resultChirho_0;
      default : \c$stChirho'_case_alt_5  = c$ds_app_arg[9604:9541];
    endcase
  end

  assign \c$stChirho'_case_alt_selection_17  = \c$stChirho'_case_scrut_0 ;

  always @(*) begin
    case(\c$stChirho'_case_alt_selection_17 )
      64'sd2 : \c$stChirho'_case_alt_6  = resultChirho_0;
      default : \c$stChirho'_case_alt_6  = c$ds_app_arg[9668:9605];
    endcase
  end

  assign \c$stChirho'_case_alt_selection_20  = \c$stChirho'_case_scrut_0 ;

  always @(*) begin
    case(\c$stChirho'_case_alt_selection_20 )
      64'sd1 : \c$stChirho'_case_alt_7  = resultChirho_0;
      default : \c$stChirho'_case_alt_7  = c$ds_app_arg[9732:9669];
    endcase
  end

  assign \c$stChirho'_case_alt_selection_23  = \c$stChirho'_case_scrut_0 ;

  always @(*) begin
    case(\c$stChirho'_case_alt_selection_23 )
      64'sd0 : \c$stChirho'_case_alt_8  = resultChirho_0;
      default : \c$stChirho'_case_alt_8  = c$ds_app_arg[9796:9733];
    endcase
  end

  assign resultChirho_0 = c$resultChirho_app_arg_2 & c$resultChirho_app_arg_1;

  assign c$vecFlat_1 = c$ds_app_arg[9796:9285];

  // index begin
  wire [63:0] vecArray_2 [0:8-1];
  genvar i_8;
  generate
  for (i_8=0; i_8 < 8; i_8=i_8+1) begin : mk_array_2
    assign vecArray_2[(8-1)-i_8] = c$vecFlat_1[i_8*64+:64];
  end
  endgenerate
  assign c$resultChirho_app_arg_1 = vecArray_2[\c$stChirho'_case_scrut_0 ];
  // index end

  assign c$vecFlat_2 = c$ds_app_arg[9796:9285];

  // index begin
  wire [63:0] vecArray_3 [0:8-1];
  genvar i_9;
  generate
  for (i_9=0; i_9 < 8; i_9=i_9+1) begin : mk_array_3
    assign vecArray_3[(8-1)-i_9] = c$vecFlat_2[i_9*64+:64];
  end
  endgenerate
  assign c$resultChirho_app_arg_2 = vecArray_3[c$resultChirho_app_arg_3];
  // index end

  assign c$resultChirho_app_arg_3 = $unsigned({{(64-3) {1'b0}},v1Chirho});

  assign v1Chirho = cmdChirho[66:64];

  assign \c$stChirho'_case_scrut_0  = $unsigned({{(64-3) {1'b0}},v2Chirho});

  assign v2Chirho = cmdChirho[63:61];


endmodule

