/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.4. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module intersect_hier_262k_chirho
    ( // Inputs
      input wire [262655:0] a_chirho
    , input wire [262655:0] b_chirho

      // Outputs
    , output wire [262655:0] result_chirho
    );
  // Hierarchical512Chirho.hs:530:1-23
  wire [262143:0] c$newBlocksChirho_case_alt;
  wire [511:0] c$app_arg;
  wire [511:0] c$app_arg_0;
  wire [262143:0] c$vec1;
  wire [262143:0] c$vec2;

  assign c$vec1 = a_chirho[262143:0];

  assign c$vec2 = b_chirho[262143:0];

  // zipWith start
  genvar i;
  generate
  for (i = 0; i < 512; i = i + 1) begin : zipWith
    wire [511:0] zipWith_in1;
    assign zipWith_in1 = c$vec1[i*512+:512];
    wire [511:0] zipWith_in2;
    assign zipWith_in2 = c$vec2[i*512+:512];
    wire [511:0] c$n;
    assign c$n = zipWith_in1 & zipWith_in2;


    assign c$newBlocksChirho_case_alt[i*512+:512] = c$n;
  end
  endgenerate
  // zipWith end

  // map begin
  genvar i_0;
  generate
  for (i_0=0; i_0 < 512; i_0 = i_0 + 1) begin : map
    wire [511:0] map_in;
    assign map_in = c$newBlocksChirho_case_alt[i_0*512+:512];
    wire  map_out;
    assign map_out = map_in != 512'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;


    assign c$app_arg[i_0*1+:1] = map_out;
  end
  endgenerate
  // map end

  // map begin
  genvar i_1;
  generate
  for (i_1=0; i_1 < 512; i_1 = i_1 + 1) begin : map_0
    wire  map_in_0;
    assign map_in_0 = c$app_arg[i_1*1+:1];
    wire [0:0] map_out_0;
    wire [0:0] c$app_arg_1;
    wire [0:0] result;
    assign map_out_0 = result;

    assign c$app_arg_1 = map_in_0 ? 1'b1 : 1'b0;

    assign result = c$app_arg_1;


    assign c$app_arg_0[i_1*1+:1] = map_out_0;
  end
  endgenerate
  // map end

  assign result_chirho = {(c$app_arg_0),
                          c$newBlocksChirho_case_alt};


endmodule

