/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.4. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module intersect_512_chirho
    ( // Inputs
      input wire [511:0] a_chirho
    , input wire [511:0] b_chirho

      // Outputs
    , output wire [511:0] result_chirho
    );


  assign result_chirho = a_chirho & b_chirho;


endmodule

