cabal-version: 2.4
name:          minikanren-clash-chirho
version:       0.1.0.0
synopsis:      1-Bit Matrix miniKanren for FPGA via Clash
license:       MIT
author:        Soli Deo Gloria
build-type:    Simple

library
  exposed-modules:
    HashConsChirho
    HbmEngineChirho
    HierarchicalChirho
    MiniKanrenChirho
  build-depends:
    base >= 4.14 && < 5,
    clash-prelude >= 1.6 && < 1.10,
    deepseq >= 1.4
  hs-source-dirs: .
  default-language: Haskell2010
  ghc-options: -Wall

test-suite quickcheck-chirho
  type:           exitcode-stdio-1.0
  main-is:        QuickCheckChirho.hs
  hs-source-dirs: test
  build-depends:
    base >= 4.14 && < 5,
    clash-prelude >= 1.6 && < 1.10,
    QuickCheck >= 2.14
  default-language: Haskell2010
  ghc-options: -Wall
