#!/bin/bash
# AWS F1 FPGA Setup Script ☧
#
# Creates the required AWS infrastructure for FPGA development.
# Part of P5-01: Physical FPGA Incarnation.
#
# "For we are labourers together with God." — 1 Corinthians 3:9

set -euo pipefail

# Configuration
REGION_CHIRHO="${AWS_REGION:-us-east-1}"
BUCKET_NAME_CHIRHO="minikanren-fpga-chirho-$(aws sts get-caller-identity --query Account --output text)"
KEY_NAME_CHIRHO="minikanren-fpga-key-chirho"
SECURITY_GROUP_CHIRHO="minikanren-fpga-sg-chirho"

echo "=== miniKanren FPGA AWS Setup ☧ ==="
echo "Region: ${REGION_CHIRHO}"
echo "Bucket: ${BUCKET_NAME_CHIRHO}"

# 1. Create S3 bucket for FPGA artifacts
echo ""
echo "[1/4] Creating S3 bucket..."
if aws s3api head-bucket --bucket "${BUCKET_NAME_CHIRHO}" 2>/dev/null; then
    echo "  Bucket already exists: ${BUCKET_NAME_CHIRHO}"
else
    aws s3api create-bucket \
        --bucket "${BUCKET_NAME_CHIRHO}" \
        --region "${REGION_CHIRHO}" \
        --create-bucket-configuration LocationConstraint="${REGION_CHIRHO}" 2>/dev/null || \
    aws s3api create-bucket \
        --bucket "${BUCKET_NAME_CHIRHO}" \
        --region "${REGION_CHIRHO}"
    echo "  Created bucket: ${BUCKET_NAME_CHIRHO}"
fi

# 2. Create SSH key pair (if not exists)
echo ""
echo "[2/4] Setting up SSH key..."
if aws ec2 describe-key-pairs --key-names "${KEY_NAME_CHIRHO}" --region "${REGION_CHIRHO}" 2>/dev/null; then
    echo "  Key pair already exists: ${KEY_NAME_CHIRHO}"
else
    aws ec2 create-key-pair \
        --key-name "${KEY_NAME_CHIRHO}" \
        --region "${REGION_CHIRHO}" \
        --query 'KeyMaterial' \
        --output text > "${HOME}/.ssh/${KEY_NAME_CHIRHO}.pem"
    chmod 600 "${HOME}/.ssh/${KEY_NAME_CHIRHO}.pem"
    echo "  Created key pair: ${KEY_NAME_CHIRHO}"
    echo "  Private key saved to: ~/.ssh/${KEY_NAME_CHIRHO}.pem"
fi

# 3. Create security group (if not exists)
echo ""
echo "[3/4] Setting up security group..."
VPC_ID_CHIRHO=$(aws ec2 describe-vpcs --region "${REGION_CHIRHO}" \
    --filters "Name=isDefault,Values=true" \
    --query "Vpcs[0].VpcId" --output text)

SG_ID_CHIRHO=$(aws ec2 describe-security-groups \
    --region "${REGION_CHIRHO}" \
    --filters "Name=group-name,Values=${SECURITY_GROUP_CHIRHO}" \
    --query "SecurityGroups[0].GroupId" --output text 2>/dev/null || echo "None")

if [ "${SG_ID_CHIRHO}" = "None" ] || [ -z "${SG_ID_CHIRHO}" ]; then
    SG_ID_CHIRHO=$(aws ec2 create-security-group \
        --group-name "${SECURITY_GROUP_CHIRHO}" \
        --description "miniKanren FPGA development security group" \
        --vpc-id "${VPC_ID_CHIRHO}" \
        --region "${REGION_CHIRHO}" \
        --query 'GroupId' --output text)

    # Allow SSH from anywhere (for development - restrict in production)
    aws ec2 authorize-security-group-ingress \
        --group-id "${SG_ID_CHIRHO}" \
        --protocol tcp \
        --port 22 \
        --cidr 0.0.0.0/0 \
        --region "${REGION_CHIRHO}"
    echo "  Created security group: ${SG_ID_CHIRHO}"
else
    echo "  Security group already exists: ${SG_ID_CHIRHO}"
fi

# 4. Save configuration
echo ""
echo "[4/4] Saving configuration..."
cat > "$(dirname "$0")/config_chirho.sh" << EOF
# AWS F1 Configuration ☧
# Generated by setup_chirho.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

export AWS_REGION_CHIRHO="${REGION_CHIRHO}"
export S3_BUCKET_CHIRHO="${BUCKET_NAME_CHIRHO}"
export KEY_NAME_CHIRHO="${KEY_NAME_CHIRHO}"
export SECURITY_GROUP_CHIRHO="${SG_ID_CHIRHO}"
export VPC_ID_CHIRHO="${VPC_ID_CHIRHO}"

# AMI IDs
export FPGA_DEV_AMI_CHIRHO="ami-01198b89d80ebfdd2"  # FPGA Developer AMI 1.17.0 Ubuntu

# Instance types
export SYNTH_INSTANCE_CHIRHO="c5.4xlarge"  # For Vivado synthesis (\$0.68/hr)
export F1_INSTANCE_CHIRHO="f1.2xlarge"     # For FPGA execution (\$1.65/hr)
EOF
echo "  Configuration saved to: config_chirho.sh"

echo ""
echo "=== Setup Complete ☧ ==="
echo ""
echo "Next steps:"
echo "  1. Upload Verilog:    ./upload_design_chirho.sh"
echo "  2. Launch synthesis:  ./launch_synth_chirho.sh"
echo "  3. Create AFI:        ./create_afi_chirho.sh"
echo "  4. Run on F1:         ./run_f1_chirho.sh"
