/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.4. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module intersect_prob_domain_64_chirho
    ( // Inputs
      input wire [1087:0] domain_a_chirho
    , input wire [1087:0] domain_b_chirho

      // Outputs
    , output wire [1087:0] domain_out_chirho
    );
  wire [1023:0] c$case_alt;
  wire [1023:0] c$vec1;
  wire [1023:0] c$vec2;

  assign c$vec1 = domain_a_chirho[1023:0];

  assign c$vec2 = domain_b_chirho[1023:0];

  // zipWith start
  genvar i;
  generate
  for (i = 0; i < 64; i = i + 1) begin : zipWith
    wire [15:0] zipWith_in1;
    assign zipWith_in1 = c$vec1[i*16+:16];
    wire [15:0] zipWith_in2;
    assign zipWith_in2 = c$vec2[i*16+:16];
    wire [15:0] c$n;
    wire [15:0] result;
    wire [15:0] a_chirho_0;
    wire [15:0] b_chirho_0;
    wire [15:0] result_chirho_0;
    assign c$n = result;

    assign a_chirho_0 = zipWith_in1;

    assign b_chirho_0 = zipWith_in2;

    soft_and_16_chirho soft_and_16_chirho_result
      (a_chirho_0, b_chirho_0, result_chirho_0);

    assign result = result_chirho_0;


    assign c$case_alt[i*16+:16] = c$n;
  end
  endgenerate
  // zipWith end

  assign domain_out_chirho = {domain_a_chirho[1087:1024] & domain_b_chirho[1087:1024],
                              c$case_alt};


endmodule

