/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.4. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module intersect_hier_134m_chirho
    ( // Inputs
      input wire [134480383:0] a_chirho
    , input wire [134480383:0] b_chirho

      // Outputs
    , output wire [134480383:0] result_chirho
    );
  // Hierarchical512Chirho.hs:700:1-23
  wire [134217727:0] c$newLevel2Chirho_case_alt;
  wire [511:0] c$app_arg;
  wire [511:0] c$app_arg_0;
  // Hierarchical512Chirho.hs:700:1-23
  wire [262143:0] newLevel1Chirho;
  wire [134217727:0] c$vec1;
  wire [134217727:0] c$vec2;

  assign c$vec1 = a_chirho[134217727:0];

  assign c$vec2 = b_chirho[134217727:0];

  // zipWith start
  genvar i_0;
  generate
  for (i_0 = 0; i_0 < 512; i_0 = i_0 + 1) begin : zipWith_0
    wire [262143:0] zipWith_in1_0;
    assign zipWith_in1_0 = c$vec1[i_0*262144+:262144];
    wire [262143:0] zipWith_in2_0;
    assign zipWith_in2_0 = c$vec2[i_0*262144+:262144];
    wire [262143:0] c$n_0;
    // zipWith start
    genvar i_6;

    for (i_6 = 0; i_6 < 512; i_6 = i_6 + 1) begin : zipWith_1
      wire [511:0] zipWith_in1_1;
      assign zipWith_in1_1 = zipWith_in1_0[i_6*512+:512];
      wire [511:0] zipWith_in2_1;
      assign zipWith_in2_1 = zipWith_in2_0[i_6*512+:512];
      wire [511:0] c$n_1;
      assign c$n_1 = zipWith_in1_1 & zipWith_in2_1;


      assign c$n_0[i_6*512+:512] = c$n_1;
    end

    // zipWith end
    assign c$newLevel2Chirho_case_alt[i_0*262144+:262144] = c$n_0;
  end
  endgenerate
  // zipWith end

  // map begin
  genvar i_1;
  generate
  for (i_1=0; i_1 < 512; i_1 = i_1 + 1) begin : map
    wire [511:0] map_in;
    assign map_in = newLevel1Chirho[i_1*512+:512];
    wire  map_out;
    assign map_out = map_in != 512'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;


    assign c$app_arg[i_1*1+:1] = map_out;
  end
  endgenerate
  // map end

  // map begin
  genvar i_2;
  generate
  for (i_2=0; i_2 < 512; i_2 = i_2 + 1) begin : map_0
    wire  map_in_0;
    assign map_in_0 = c$app_arg[i_2*1+:1];
    wire [0:0] map_out_0;
    wire [0:0] c$app_arg_1;
    wire [0:0] result;
    assign map_out_0 = result;

    assign c$app_arg_1 = map_in_0 ? 1'b1 : 1'b0;

    assign result = c$app_arg_1;


    assign c$app_arg_0[i_2*1+:1] = map_out_0;
  end
  endgenerate
  // map end

  assign result_chirho = {(c$app_arg_0),
                          newLevel1Chirho,   c$newLevel2Chirho_case_alt};

  // map begin
  genvar i_5;
  generate
  for (i_5=0; i_5 < 512; i_5 = i_5 + 1) begin : map_3
    wire [262143:0] map_in_3;
    assign map_in_3 = c$newLevel2Chirho_case_alt[i_5*262144+:262144];
    wire [511:0] map_out_3;
    wire [511:0] c$app_arg_2;
    wire [511:0] c$app_arg_3;
    wire [511:0] result_0;
    assign map_out_3 = result_0;

    // map begin
    genvar i_3;

    for (i_3=0; i_3 < 512; i_3 = i_3 + 1) begin : map_1
      wire  map_in_1;
      assign map_in_1 = c$app_arg_3[i_3*1+:1];
      wire [0:0] map_out_1;
      wire [0:0] c$app_arg_4;
    wire [0:0] result_1;
    assign map_out_1 = result_1;

    assign c$app_arg_4 = map_in_1 ? 1'b1 : 1'b0;

    assign result_1 = c$app_arg_4;


      assign c$app_arg_2[i_3*1+:1] = map_out_1;
    end

    // map end

    // map begin
    genvar i_4;

    for (i_4=0; i_4 < 512; i_4 = i_4 + 1) begin : map_2
      wire [511:0] map_in_2;
      assign map_in_2 = map_in_3[i_4*512+:512];
      wire  map_out_2;
      assign map_out_2 = map_in_2 != 512'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;


      assign c$app_arg_3[i_4*1+:1] = map_out_2;
    end

    // map end

    assign result_0 = (c$app_arg_2);


    assign newLevel1Chirho[i_5*512+:512] = map_out_3;
  end
  endgenerate
  // map end


endmodule

