/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.4. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module soft_and_16_chirho
    ( // Inputs
      input wire [15:0] a_chirho
    , input wire [15:0] b_chirho

      // Outputs
    , output wire [15:0] result_chirho
    );
  // DiffFixedChirho.hs:91:1-15
  wire [31:0] karg;

  assign karg = (({16'b0000000000000000,a_chirho}) * ({16'b0000000000000000,b_chirho})) >> (64'sd16);

  assign result_chirho = karg[0+:16];


endmodule

