/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.4. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module soft_and_32_chirho
    ( // Inputs
      input wire [31:0] a_chirho
    , input wire [31:0] b_chirho

      // Outputs
    , output wire [31:0] result_chirho
    );
  // DiffFixedChirho.hs:137:1-15
  wire [63:0] karg;

  assign karg = (({32'b00000000000000000000000000000000,a_chirho}) * ({32'b00000000000000000000000000000000,b_chirho})) >> (64'sd32);

  assign result_chirho = karg[0+:32];


endmodule

